/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2o_r0 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w2048,
    w2047,
    w16,
    w17,
    w8,
    w25,
    w136,
    w153,
    w612,
    w1435,
    w4352,
    w4377,
    w1600,
    w447,
    w894,
    w919,
    w3576,
    w3729,
    w4799,
    w1838,
    w1391,
    w1531,
    w1374,
    w687,
    w5064,
    w633,
    w5063,
    w6400,
    w7033,
    w10126,
    w5749,
    w3702,
    w1851,
    w7123,
    w19584,
    w14785,
    w12800,
    w1985,
    w9598,
    w5187,
    w2870,
    w1339,
    w5356,
    w6695,
    w2678,
    w8427,
    w800,
    w2047_,
    w2448,
    w2532,
    w2532_,
    w3970,
    w3970_,
    w2782,
    w2782_,
    w7033_,
    w6124,
    w1435_,
    w4799_,
    w5187_,
    w6695_,
    w4377_,
    w1838_;

  assign w1 = X;
  assign w2048 = w1 << 11;
  assign w2047 = w2048 - w1;
  assign w16 = w1 << 4;
  assign w17 = w1 + w16;
  assign w8 = w1 << 3;
  assign w25 = w17 + w8;
  assign w136 = w17 << 3;
  assign w153 = w17 + w136;
  assign w612 = w153 << 2;
  assign w1435 = w2047 - w612;
  assign w4352 = w17 << 8;
  assign w4377 = w25 + w4352;
  assign w1600 = w25 << 6;
  assign w447 = w2047 - w1600;
  assign w894 = w447 << 1;
  assign w919 = w25 + w894;
  assign w3576 = w447 << 3;
  assign w3729 = w153 + w3576;
  assign w4799 = w447 + w4352;
  assign w1838 = w919 << 1;
  assign w1391 = w1838 - w447;
  assign w1531 = w919 + w612;
  assign w1374 = w1391 - w17;
  assign w687 = w1374 >> 1;
  assign w5064 = w4377 + w687;
  assign w633 = w5064 >> 3;
  assign w5063 = w5064 - w1;
  assign w6400 = w25 << 8;
  assign w7033 = w633 + w6400;
  assign w10126 = w5063 << 1;
  assign w5749 = w10126 - w4377;
  assign w3702 = w5749 - w2047;
  assign w1851 = w3702 >> 1;
  assign w7123 = w5749 + w1374;
  assign w19584 = w153 << 7;
  assign w14785 = w19584 - w4799;
  assign w12800 = w25 << 9;
  assign w1985 = w14785 - w12800;
  assign w9598 = w4799 << 1;
  assign w5187 = w14785 - w9598;
  assign w2870 = w1435 << 1;
  assign w1339 = w2870 - w1531;
  assign w5356 = w1339 << 2;
  assign w6695 = w1339 + w5356;
  assign w2678 = w1339 << 1;
  assign w8427 = w5749 + w2678;
  assign w800 = w25 << 5;
  assign w2047_ = -1 * w2047;
  assign w2448 = w153 << 4;
  assign w2532 = w633 << 2;
  assign w2532_ = -1 * w2532;
  assign w3970 = w1985 << 1;
  assign w3970_ = -1 * w3970;
  assign w2782 = w1391 << 1;
  assign w2782_ = -1 * w2782;
  assign w7033_ = -1 * w7033;
  assign w6124 = w1531 << 2;
  assign w1435_ = -1 * w1435;
  assign w4799_ = -1 * w4799;
  assign w5187_ = -1 * w5187;
  assign w6695_ = -1 * w6695;
  assign w4377_ = -1 * w4377;
  assign w1838_ = -1 * w1838;

  assign Y[0] = w800[46:15];
  assign Y[1] = w2047_[46:15];
  assign Y[2] = w1374[46:15];
  assign Y[3] = w2448[46:15];
  assign Y[4] = w2532_[46:15];
  assign Y[5] = w3970_[46:15];
  assign Y[6] = w2782_[46:15];
  assign Y[7] = w5063[46:15];
  assign Y[8] = w7033_[46:15];
  assign Y[9] = w6124[46:15];
  assign Y[10] = w1435_[46:15];
  assign Y[11] = w3729[46:15];
  assign Y[12] = w4799_[46:15];
  assign Y[13] = w7123[46:15];
  assign Y[14] = w1851[46:15];
  assign Y[15] = w5187_[46:15];
  assign Y[16] = w8427[46:15];
  assign Y[17] = w6695_[46:15];
  assign Y[18] = w4377_[46:15];
  assign Y[19] = w1838_[46:15];

endmodule //multiplier_block
