/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_i2h_r0 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w8,
    w9,
    w128,
    w119,
    w15232,
    w15231,
    w4096,
    w3977,
    w2,
    w3979,
    w4,
    w3981,
    w2304,
    w1675,
    w16384,
    w12405,
    w18,
    w12387,
    w16501,
    w238,
    w4219,
    w2048,
    w2171,
    w24774,
    w20555,
    w6700,
    w23201,
    w144,
    w23057,
    w64,
    w23265,
    w23176,
    w2897,
    w11588,
    w8967,
    w10789,
    w17934,
    w20105,
    w40210,
    w19655,
    w5794,
    w25899,
    w13400,
    w1831,
    w7324,
    w3347,
    w25007,
    w6694,
    w8537,
    w33544,
    w4193,
    w17074,
    w17065,
    w80420,
    w96921,
    w63696,
    w33225,
    w60928,
    w84129,
    w58592,
    w25537,
    w10789_,
    w23057_,
    w25007_,
    w7958,
    w7958_,
    w20555_,
    w23265_,
    w8967_,
    w24774_,
    w25899_,
    w33002,
    w33002_,
    w17065_,
    w15924,
    w15924_,
    w34736,
    w33225_,
    w26800,
    w26800_,
    w4193_;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w9 = w1 + w8;
  assign w128 = w1 << 7;
  assign w119 = w128 - w9;
  assign w15232 = w119 << 7;
  assign w15231 = w15232 - w1;
  assign w4096 = w1 << 12;
  assign w3977 = w4096 - w119;
  assign w2 = w1 << 1;
  assign w3979 = w3977 + w2;
  assign w4 = w1 << 2;
  assign w3981 = w3977 + w4;
  assign w2304 = w9 << 8;
  assign w1675 = w3979 - w2304;
  assign w16384 = w1 << 14;
  assign w12405 = w16384 - w3979;
  assign w18 = w9 << 1;
  assign w12387 = w12405 - w18;
  assign w16501 = w12405 + w4096;
  assign w238 = w119 << 1;
  assign w4219 = w3981 + w238;
  assign w2048 = w1 << 11;
  assign w2171 = w4219 - w2048;
  assign w24774 = w12387 << 1;
  assign w20555 = w24774 - w4219;
  assign w6700 = w1675 << 2;
  assign w23201 = w16501 + w6700;
  assign w144 = w9 << 4;
  assign w23057 = w23201 - w144;
  assign w64 = w1 << 6;
  assign w23265 = w23201 + w64;
  assign w23176 = w119 + w23057;
  assign w2897 = w23176 >> 3;
  assign w11588 = w2897 << 2;
  assign w8967 = w20555 - w11588;
  assign w10789 = w23176 - w12387;
  assign w17934 = w8967 << 1;
  assign w20105 = w2171 + w17934;
  assign w40210 = w20105 << 1;
  assign w19655 = w40210 - w20555;
  assign w5794 = w2897 << 1;
  assign w25899 = w20105 + w5794;
  assign w13400 = w1675 << 3;
  assign w1831 = w15231 - w13400;
  assign w7324 = w1831 << 2;
  assign w3347 = w7324 - w3977;
  assign w25007 = w1831 + w23176;
  assign w6694 = w3347 << 1;
  assign w8537 = w15231 - w6694;
  assign w33544 = w25007 + w8537;
  assign w4193 = w33544 >> 3;
  assign w17074 = w8537 << 1;
  assign w17065 = w17074 - w9;
  assign w80420 = w20105 << 2;
  assign w96921 = w16501 + w80420;
  assign w63696 = w3981 << 4;
  assign w33225 = w96921 - w63696;
  assign w60928 = w119 << 9;
  assign w84129 = w23201 + w60928;
  assign w58592 = w1831 << 5;
  assign w25537 = w84129 - w58592;
  assign w10789_ = -1 * w10789;
  assign w23057_ = -1 * w23057;
  assign w25007_ = -1 * w25007;
  assign w7958 = w3979 << 1;
  assign w7958_ = -1 * w7958;
  assign w20555_ = -1 * w20555;
  assign w23265_ = -1 * w23265;
  assign w8967_ = -1 * w8967;
  assign w24774_ = -1 * w24774;
  assign w25899_ = -1 * w25899;
  assign w33002 = w16501 << 1;
  assign w33002_ = -1 * w33002;
  assign w17065_ = -1 * w17065;
  assign w15924 = w3981 << 2;
  assign w15924_ = -1 * w15924;
  assign w34736 = w2171 << 4;
  assign w33225_ = -1 * w33225;
  assign w26800 = w1675 << 4;
  assign w26800_ = -1 * w26800;
  assign w4193_ = -1 * w4193;

  assign Y[0] = w10789_[46:15];
  assign Y[1] = w23057_[46:15];
  assign Y[2] = w25007_[46:15];
  assign Y[3] = w7958_[46:15];
  assign Y[4] = w20555_[46:15];
  assign Y[5] = w23265_[46:15];
  assign Y[6] = w8967_[46:15];
  assign Y[7] = w24774_[46:15];
  assign Y[8] = w25899_[46:15];
  assign Y[9] = w3347[46:15];
  assign Y[10] = w33002_[46:15];
  assign Y[11] = w17065_[46:15];
  assign Y[12] = w15924_[46:15];
  assign Y[13] = w34736[46:15];
  assign Y[14] = w19655[46:15];
  assign Y[15] = w33225_[46:15];
  assign Y[16] = w26800_[46:15];
  assign Y[17] = w4193_[46:15];
  assign Y[18] = w15231[46:15];
  assign Y[19] = w25537[46:15];

endmodule //multiplier_block
