/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r19 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [51:0]
    w1,
    w256,
    w257,
    w8,
    w9,
    w9216,
    w9473,
    w9465,
    w32768,
    w32759,
    w8224,
    w24535,
    w131036,
    w140509,
    w514,
    w9987,
    w1024,
    w11011,
    w39948,
    w39691,
    w79382,
    w79125,
    w158250,
    w167715,
    w4608,
    w29143,
    w58286,
    w58277,
    w316500,
    w345643,
    w32896,
    w3753,
    w576,
    w3177,
    w319584,
    w319585,
    w279894,
    w139947,
    w50832,
    w268753,
    w12708,
    w332935,
    w1028,
    w331907,
    w262144,
    w607787,
    w480384,
    w127403,
    w303136,
    w443083,
    w403392,
    w6303,
    w427927,
    w524144,
    w96217,
    w262072,
    w689999,
    w1009584,
    w63099,
    w562036,
    w907679,
    w217680,
    w13605,
    w406656,
    w574371,
    w574380,
    w143595,
    w16448,
    w590819,
    w147736,
    w18467,
    w201696,
    w341643,
    w323176,
    w40397,
    w24535_,
    w126198,
    w126198_,
    w12708_,
    w79382_,
    w281018,
    w281018_,
    w88088,
    w345643_,
    w116554,
    w116554_,
    w268753_,
    w201696_,
    w37860,
    w331907_,
    w27210,
    w27210_,
    w147736_;

  assign w1 = X;
  assign w256 = w1 << 8;
  assign w257 = w1 + w256;
  assign w8 = w1 << 3;
  assign w9 = w1 + w8;
  assign w9216 = w9 << 10;
  assign w9473 = w257 + w9216;
  assign w9465 = w9473 - w8;
  assign w32768 = w1 << 15;
  assign w32759 = w32768 - w9;
  assign w8224 = w257 << 5;
  assign w24535 = w32759 - w8224;
  assign w131036 = w32759 << 2;
  assign w140509 = w9473 + w131036;
  assign w514 = w257 << 1;
  assign w9987 = w9473 + w514;
  assign w1024 = w1 << 10;
  assign w11011 = w9987 + w1024;
  assign w39948 = w9987 << 2;
  assign w39691 = w39948 - w257;
  assign w79382 = w39691 << 1;
  assign w79125 = w79382 - w257;
  assign w158250 = w79125 << 1;
  assign w167715 = w9465 + w158250;
  assign w4608 = w9 << 9;
  assign w29143 = w24535 + w4608;
  assign w58286 = w29143 << 1;
  assign w58277 = w58286 - w9;
  assign w316500 = w79125 << 2;
  assign w345643 = w29143 + w316500;
  assign w32896 = w257 << 7;
  assign w3753 = w32896 - w29143;
  assign w576 = w9 << 6;
  assign w3177 = w3753 - w576;
  assign w319584 = w9987 << 5;
  assign w319585 = w1 + w319584;
  assign w279894 = w319585 - w39691;
  assign w139947 = w279894 >> 1;
  assign w50832 = w3177 << 4;
  assign w268753 = w319585 - w50832;
  assign w12708 = w3177 << 2;
  assign w332935 = w345643 - w12708;
  assign w1028 = w257 << 2;
  assign w331907 = w332935 - w1028;
  assign w262144 = w1 << 18;
  assign w607787 = w345643 + w262144;
  assign w480384 = w3753 << 7;
  assign w127403 = w607787 - w480384;
  assign w303136 = w9473 << 5;
  assign w443083 = w139947 + w303136;
  assign w403392 = w443083 - w39691;
  assign w6303 = w403392 >> 6;
  assign w427927 = w24535 + w403392;
  assign w524144 = w32759 << 4;
  assign w96217 = w524144 - w427927;
  assign w262072 = w32759 << 3;
  assign w689999 = w427927 + w262072;
  assign w1009584 = w319585 + w689999;
  assign w63099 = w1009584 >> 4;
  assign w562036 = w140509 << 2;
  assign w907679 = w345643 + w562036;
  assign w217680 = w907679 - w689999;
  assign w13605 = w217680 >> 4;
  assign w406656 = w3177 << 7;
  assign w574371 = w167715 + w406656;
  assign w574380 = w9 + w574371;
  assign w143595 = w574380 >> 2;
  assign w16448 = w257 << 6;
  assign w590819 = w574371 + w16448;
  assign w147736 = w590819 - w443083;
  assign w18467 = w147736 >> 3;
  assign w201696 = w6303 << 5;
  assign w341643 = w139947 + w201696;
  assign w323176 = w341643 - w18467;
  assign w40397 = w323176 >> 3;
  assign w24535_ = -1 * w24535;
  assign w126198 = w63099 << 1;
  assign w126198_ = -1 * w126198;
  assign w12708_ = -1 * w12708;
  assign w79382_ = -1 * w79382;
  assign w281018 = w140509 << 1;
  assign w281018_ = -1 * w281018;
  assign w88088 = w11011 << 3;
  assign w345643_ = -1 * w345643;
  assign w116554 = w58277 << 1;
  assign w116554_ = -1 * w116554;
  assign w268753_ = -1 * w268753;
  assign w201696_ = -1 * w201696;
  assign w37860 = w9465 << 2;
  assign w331907_ = -1 * w331907;
  assign w27210 = w13605 << 1;
  assign w27210_ = -1 * w27210;
  assign w147736_ = -1 * w147736;

  assign Y[0] = w24535_[51:20];
  assign Y[1] = w126198_[51:20];
  assign Y[2] = w12708_[51:20];
  assign Y[3] = w79382_[51:20];
  assign Y[4] = w96217[51:20];
  assign Y[5] = w281018_[51:20];
  assign Y[6] = w88088[51:20];
  assign Y[7] = w40397[51:20];
  assign Y[8] = w139947[51:20];
  assign Y[9] = w345643_[51:20];
  assign Y[10] = w116554_[51:20];
  assign Y[11] = w127403[51:20];
  assign Y[12] = w268753_[51:20];
  assign Y[13] = w201696_[51:20];
  assign Y[14] = w143595[51:20];
  assign Y[15] = w37860[51:20];
  assign Y[16] = w331907_[51:20];
  assign Y[17] = w27210_[51:20];
  assign Y[18] = w147736_[51:20];
  assign Y[19] = w167715[51:20];

endmodule //multiplier_block
