/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r1 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [51:0]
    w1,
    w128,
    w127,
    w4064,
    w4191,
    w16764,
    w20955,
    w32768,
    w11813,
    w8,
    w4199,
    w8398,
    w8397,
    w23626,
    w23625,
    w94500,
    w98699,
    w2670,
    w1335,
    w42720,
    w21765,
    w2,
    w8395,
    w16790,
    w18125,
    w34325,
    w508,
    w24133,
    w48266,
    w71891,
    w274600,
    w175901,
    w2048,
    w173853,
    w537472,
    w533281,
    w335280,
    w198001,
    w33528,
    w566809,
    w580000,
    w13191,
    w268736,
    w303061,
    w47252,
    w350313,
    w348240,
    w651301,
    w672256,
    w1313,
    w396002,
    w746315,
    w670560,
    w75755,
    w268640,
    w477675,
    w405784,
    w50723,
    w341760,
    w337569,
    w134368,
    w203201,
    w94504,
    w438777,
    w378000,
    w60777,
    w812804,
    w873581,
    w844224,
    w29357,
    w812955,
    w232955,
    w197398,
    w163073,
    w84032,
    w79041,
    w652292,
    w656491,
    w524288,
    w132203,
    w68650,
    w101446,
    w101446_,
    w174120,
    w98699_,
    w94504_,
    w158082,
    w232955_,
    w121554,
    w121554_,
    w117428,
    w105528,
    w105528_,
    w151510,
    w151510_,
    w350313_,
    w134352,
    w134352_;

  assign w1 = X;
  assign w128 = w1 << 7;
  assign w127 = w128 - w1;
  assign w4064 = w127 << 5;
  assign w4191 = w127 + w4064;
  assign w16764 = w4191 << 2;
  assign w20955 = w4191 + w16764;
  assign w32768 = w1 << 15;
  assign w11813 = w32768 - w20955;
  assign w8 = w1 << 3;
  assign w4199 = w4191 + w8;
  assign w8398 = w4199 << 1;
  assign w8397 = w8398 - w1;
  assign w23626 = w11813 << 1;
  assign w23625 = w23626 - w1;
  assign w94500 = w23625 << 2;
  assign w98699 = w4199 + w94500;
  assign w2670 = w23625 - w20955;
  assign w1335 = w2670 >> 1;
  assign w42720 = w1335 << 5;
  assign w21765 = w42720 - w20955;
  assign w2 = w1 << 1;
  assign w8395 = w8397 - w2;
  assign w16790 = w8395 << 1;
  assign w18125 = w1335 + w16790;
  assign w34325 = w42720 - w8395;
  assign w508 = w127 << 2;
  assign w24133 = w23625 + w508;
  assign w48266 = w24133 << 1;
  assign w71891 = w23625 + w48266;
  assign w274600 = w34325 << 3;
  assign w175901 = w274600 - w98699;
  assign w2048 = w1 << 11;
  assign w173853 = w175901 - w2048;
  assign w537472 = w4199 << 7;
  assign w533281 = w537472 - w4191;
  assign w335280 = w20955 << 4;
  assign w198001 = w533281 - w335280;
  assign w33528 = w4191 << 3;
  assign w566809 = w533281 + w33528;
  assign w580000 = w18125 << 5;
  assign w13191 = w580000 - w566809;
  assign w268736 = w4199 << 6;
  assign w303061 = w34325 + w268736;
  assign w47252 = w11813 << 2;
  assign w350313 = w303061 + w47252;
  assign w348240 = w21765 << 4;
  assign w651301 = w303061 + w348240;
  assign w672256 = w20955 + w651301;
  assign w1313 = w672256 >> 9;
  assign w396002 = w198001 << 1;
  assign w746315 = w350313 + w396002;
  assign w670560 = w20955 << 5;
  assign w75755 = w746315 - w670560;
  assign w268640 = w8395 << 5;
  assign w477675 = w746315 - w268640;
  assign w405784 = w477675 - w71891;
  assign w50723 = w405784 >> 3;
  assign w341760 = w1335 << 8;
  assign w337569 = w341760 - w4191;
  assign w134368 = w4199 << 5;
  assign w203201 = w337569 - w134368;
  assign w94504 = w11813 << 3;
  assign w438777 = w533281 - w94504;
  assign w378000 = w23625 << 4;
  assign w60777 = w438777 - w378000;
  assign w812804 = w203201 << 2;
  assign w873581 = w60777 + w812804;
  assign w844224 = w13191 << 6;
  assign w29357 = w873581 - w844224;
  assign w812955 = w477675 + w335280;
  assign w232955 = w812955 - w580000;
  assign w197398 = w98699 << 1;
  assign w163073 = w197398 - w34325;
  assign w84032 = w1313 << 6;
  assign w79041 = w163073 - w84032;
  assign w652292 = w163073 << 2;
  assign w656491 = w4199 + w652292;
  assign w524288 = w1 << 19;
  assign w132203 = w656491 - w524288;
  assign w68650 = w34325 << 1;
  assign w101446 = w50723 << 1;
  assign w101446_ = -1 * w101446;
  assign w174120 = w21765 << 3;
  assign w98699_ = -1 * w98699;
  assign w94504_ = -1 * w94504;
  assign w158082 = w79041 << 1;
  assign w232955_ = -1 * w232955;
  assign w121554 = w60777 << 1;
  assign w121554_ = -1 * w121554;
  assign w117428 = w29357 << 2;
  assign w105528 = w13191 << 3;
  assign w105528_ = -1 * w105528;
  assign w151510 = w75755 << 1;
  assign w151510_ = -1 * w151510;
  assign w350313_ = -1 * w350313;
  assign w134352 = w8397 << 4;
  assign w134352_ = -1 * w134352;

  assign Y[0] = w71891[51:20];
  assign Y[1] = w132203[51:20];
  assign Y[2] = w68650[51:20];
  assign Y[3] = w101446_[51:20];
  assign Y[4] = w174120[51:20];
  assign Y[5] = w98699_[51:20];
  assign Y[6] = w94504_[51:20];
  assign Y[7] = w158082[51:20];
  assign Y[8] = w232955_[51:20];
  assign Y[9] = w1313[51:20];
  assign Y[10] = w121554_[51:20];
  assign Y[11] = w203201[51:20];
  assign Y[12] = w117428[51:20];
  assign Y[13] = w198001[51:20];
  assign Y[14] = w18125[51:20];
  assign Y[15] = w105528_[51:20];
  assign Y[16] = w173853[51:20];
  assign Y[17] = w151510_[51:20];
  assign Y[18] = w350313_[51:20];
  assign Y[19] = w134352_[51:20];

endmodule //multiplier_block