/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r3 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [51:0]
    w1,
    w8,
    w7,
    w224,
    w231,
    w924,
    w1155,
    w14784,
    w14777,
    w236432,
    w221655,
    w131072,
    w90583,
    w57344,
    w147927,
    w14336,
    w76247,
    w56,
    w76191,
    w7392,
    w68855,
    w68856,
    w8607,
    w68631,
    w57575,
    w7168,
    w64743,
    w1848,
    w1849,
    w7396,
    w61235,
    w244940,
    w244941,
    w309684,
    w77421,
    w118336,
    w126605,
    w64,
    w65,
    w77356,
    w19339,
    w4160,
    w57075,
    w448,
    w61683,
    w123366,
    w54511,
    w133120,
    w71437,
    w458752,
    w458745,
    w362332,
    w96413,
    w58924,
    w14731,
    w111144,
    w13893,
    w235696,
    w235761,
    w436289,
    w379214,
    w189607,
    w262144,
    w451751,
    w246732,
    w205019,
    w471522,
    w395331,
    w222288,
    w173043,
    w258972,
    w19339_,
    w152382,
    w73920,
    w73920_,
    w142874,
    w54511_,
    w205019_,
    w68631_,
    w173043_,
    w235761_,
    w253210,
    w253210_,
    w61235_,
    w96413_,
    w154842;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w7 = w8 - w1;
  assign w224 = w7 << 5;
  assign w231 = w7 + w224;
  assign w924 = w231 << 2;
  assign w1155 = w231 + w924;
  assign w14784 = w231 << 6;
  assign w14777 = w14784 - w7;
  assign w236432 = w14777 << 4;
  assign w221655 = w236432 - w14777;
  assign w131072 = w1 << 17;
  assign w90583 = w221655 - w131072;
  assign w57344 = w7 << 13;
  assign w147927 = w90583 + w57344;
  assign w14336 = w7 << 11;
  assign w76247 = w90583 - w14336;
  assign w56 = w7 << 3;
  assign w76191 = w76247 - w56;
  assign w7392 = w231 << 5;
  assign w68855 = w76247 - w7392;
  assign w68856 = w1 + w68855;
  assign w8607 = w68856 >> 3;
  assign w68631 = w68855 - w224;
  assign w57575 = w231 + w57344;
  assign w7168 = w7 << 10;
  assign w64743 = w57575 + w7168;
  assign w1848 = w231 << 3;
  assign w1849 = w1 + w1848;
  assign w7396 = w1849 << 2;
  assign w61235 = w68631 - w7396;
  assign w244940 = w61235 << 2;
  assign w244941 = w1 + w244940;
  assign w309684 = w64743 + w244941;
  assign w77421 = w309684 >> 2;
  assign w118336 = w1849 << 6;
  assign w126605 = w244941 - w118336;
  assign w64 = w1 << 6;
  assign w65 = w1 + w64;
  assign w77356 = w77421 - w65;
  assign w19339 = w77356 >> 2;
  assign w4160 = w65 << 6;
  assign w57075 = w61235 - w4160;
  assign w448 = w7 << 6;
  assign w61683 = w61235 + w448;
  assign w123366 = w61683 << 1;
  assign w54511 = w123366 - w68855;
  assign w133120 = w65 << 11;
  assign w71437 = w133120 - w61683;
  assign w458752 = w7 << 16;
  assign w458745 = w458752 - w7;
  assign w362332 = w90583 << 2;
  assign w96413 = w458745 - w362332;
  assign w58924 = w1849 + w57075;
  assign w14731 = w58924 >> 2;
  assign w111144 = w96413 + w14731;
  assign w13893 = w111144 >> 3;
  assign w235696 = w14731 << 4;
  assign w235761 = w65 + w235696;
  assign w436289 = w126605 + w309684;
  assign w379214 = w436289 - w57075;
  assign w189607 = w379214 >> 1;
  assign w262144 = w1 << 18;
  assign w451751 = w189607 + w262144;
  assign w246732 = w61683 << 2;
  assign w205019 = w451751 - w246732;
  assign w471522 = w235761 << 1;
  assign w395331 = w471522 - w76191;
  assign w222288 = w13893 << 4;
  assign w173043 = w395331 - w222288;
  assign w258972 = w64743 << 2;
  assign w19339_ = -1 * w19339;
  assign w152382 = w76191 << 1;
  assign w73920 = w1155 << 6;
  assign w73920_ = -1 * w73920;
  assign w142874 = w71437 << 1;
  assign w54511_ = -1 * w54511;
  assign w205019_ = -1 * w205019;
  assign w68631_ = -1 * w68631;
  assign w173043_ = -1 * w173043;
  assign w235761_ = -1 * w235761;
  assign w253210 = w126605 << 1;
  assign w253210_ = -1 * w253210;
  assign w61235_ = -1 * w61235;
  assign w96413_ = -1 * w96413;
  assign w154842 = w77421 << 1;

  assign Y[0] = w258972[51:20];
  assign Y[1] = w19339_[51:20];
  assign Y[2] = w152382[51:20];
  assign Y[3] = w73920_[51:20];
  assign Y[4] = w142874[51:20];
  assign Y[5] = w54511_[51:20];
  assign Y[6] = w205019_[51:20];
  assign Y[7] = w68631_[51:20];
  assign Y[8] = w13893[51:20];
  assign Y[9] = w173043_[51:20];
  assign Y[10] = w235761_[51:20];
  assign Y[11] = w253210_[51:20];
  assign Y[12] = w147927[51:20];
  assign Y[13] = w221655[51:20];
  assign Y[14] = w57075[51:20];
  assign Y[15] = w61235_[51:20];
  assign Y[16] = w96413_[51:20];
  assign Y[17] = w189607[51:20];
  assign Y[18] = w68856[51:20];
  assign Y[19] = w154842[51:20];

endmodule //multiplier_block