/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r16 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [51:0]
    w1,
    w4,
    w5,
    w128,
    w129,
    w8256,
    w8127,
    w134,
    w67,
    w327680,
    w327747,
    w65016,
    w65083,
    w268,
    w64815,
    w56956,
    w14239,
    w512,
    w13727,
    w1024,
    w15263,
    w536,
    w14727,
    w64,
    w14663,
    w29454,
    w43181,
    w516,
    w65331,
    w65267,
    w51437,
    w102874,
    w37543,
    w640,
    w64175,
    w20,
    w64155,
    w1045296,
    w980029,
    w988156,
    w247039,
    w411496,
    w419623,
    w419622,
    w209811,
    w2,
    w247037,
    w232310,
    w116155,
    w327107,
    w574144,
    w8971,
    w297125,
    w5120,
    w302245,
    w130166,
    w432411,
    w439264,
    w6853,
    w16384,
    w448795,
    w690896,
    w242101,
    w1032,
    w301213,
    w10240,
    w290973,
    w131072,
    w131071,
    w219632,
    w88561,
    w274432,
    w282559,
    w260332,
    w22227,
    w513240,
    w354244,
    w122104,
    w122104_,
    w27454,
    w64815_,
    w75086,
    w75086_,
    w219296,
    w219296_,
    w8127_,
    w234608,
    w35884,
    w44454,
    w44454_,
    w86362,
    w86362_,
    w261068,
    w261068_,
    w209811_;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w5 = w1 + w4;
  assign w128 = w1 << 7;
  assign w129 = w1 + w128;
  assign w8256 = w129 << 6;
  assign w8127 = w8256 - w129;
  assign w134 = w5 + w129;
  assign w67 = w134 >> 1;
  assign w327680 = w5 << 16;
  assign w327747 = w67 + w327680;
  assign w65016 = w8127 << 3;
  assign w65083 = w67 + w65016;
  assign w268 = w67 << 2;
  assign w64815 = w65083 - w268;
  assign w56956 = w65083 - w8127;
  assign w14239 = w56956 >> 2;
  assign w512 = w1 << 9;
  assign w13727 = w14239 - w512;
  assign w1024 = w1 << 10;
  assign w15263 = w14239 + w1024;
  assign w536 = w67 << 3;
  assign w14727 = w15263 - w536;
  assign w64 = w1 << 6;
  assign w14663 = w14727 - w64;
  assign w29454 = w14727 << 1;
  assign w43181 = w13727 + w29454;
  assign w516 = w129 << 2;
  assign w65331 = w64815 + w516;
  assign w65267 = w65331 - w64;
  assign w51437 = w43181 + w8256;
  assign w102874 = w51437 << 1;
  assign w37543 = w102874 - w65331;
  assign w640 = w5 << 7;
  assign w64175 = w64815 - w640;
  assign w20 = w5 << 2;
  assign w64155 = w64175 - w20;
  assign w1045296 = w65331 << 4;
  assign w980029 = w1045296 - w65267;
  assign w988156 = w8127 + w980029;
  assign w247039 = w988156 >> 2;
  assign w411496 = w51437 << 3;
  assign w419623 = w8127 + w411496;
  assign w419622 = w419623 - w1;
  assign w209811 = w419622 >> 1;
  assign w2 = w1 << 1;
  assign w247037 = w247039 - w2;
  assign w232310 = w247037 - w14727;
  assign w116155 = w232310 >> 1;
  assign w327107 = w327747 - w640;
  assign w574144 = w247037 + w327107;
  assign w8971 = w574144 >> 6;
  assign w297125 = w64815 + w232310;
  assign w5120 = w5 << 10;
  assign w302245 = w297125 + w5120;
  assign w130166 = w65083 << 1;
  assign w432411 = w302245 + w130166;
  assign w439264 = w13727 << 5;
  assign w6853 = w439264 - w432411;
  assign w16384 = w1 << 14;
  assign w448795 = w432411 + w16384;
  assign w690896 = w43181 << 4;
  assign w242101 = w690896 - w448795;
  assign w1032 = w129 << 3;
  assign w301213 = w302245 - w1032;
  assign w10240 = w5 << 11;
  assign w290973 = w301213 - w10240;
  assign w131072 = w1 << 17;
  assign w131071 = w131072 - w1;
  assign w219632 = w13727 << 4;
  assign w88561 = w219632 - w131071;
  assign w274432 = w67 << 12;
  assign w282559 = w8127 + w274432;
  assign w260332 = w65083 << 2;
  assign w22227 = w282559 - w260332;
  assign w513240 = w64155 << 3;
  assign w354244 = w88561 << 2;
  assign w122104 = w15263 << 3;
  assign w122104_ = -1 * w122104;
  assign w27454 = w13727 << 1;
  assign w64815_ = -1 * w64815;
  assign w75086 = w37543 << 1;
  assign w75086_ = -1 * w75086;
  assign w219296 = w6853 << 5;
  assign w219296_ = -1 * w219296;
  assign w8127_ = -1 * w8127;
  assign w234608 = w14663 << 4;
  assign w35884 = w8971 << 2;
  assign w44454 = w22227 << 1;
  assign w44454_ = -1 * w44454;
  assign w86362 = w43181 << 1;
  assign w86362_ = -1 * w86362;
  assign w261068 = w65267 << 2;
  assign w261068_ = -1 * w261068;
  assign w209811_ = -1 * w209811;

  assign Y[0] = w327747[51:20];
  assign Y[1] = w290973[51:20];
  assign Y[2] = w513240[51:20];
  assign Y[3] = w354244[51:20];
  assign Y[4] = w122104_[51:20];
  assign Y[5] = w27454[51:20];
  assign Y[6] = w64815_[51:20];
  assign Y[7] = w75086_[51:20];
  assign Y[8] = w116155[51:20];
  assign Y[9] = w219296_[51:20];
  assign Y[10] = w8127_[51:20];
  assign Y[11] = w234608[51:20];
  assign Y[12] = w302245[51:20];
  assign Y[13] = w35884[51:20];
  assign Y[14] = w44454_[51:20];
  assign Y[15] = w86362_[51:20];
  assign Y[16] = w247039[51:20];
  assign Y[17] = w242101[51:20];
  assign Y[18] = w261068_[51:20];
  assign Y[19] = w209811_[51:20];

endmodule //multiplier_block