/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r13 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [51:0]
    w1,
    w256,
    w255,
    w4,
    w251,
    w8032,
    w8283,
    w33132,
    w33131,
    w8,
    w9,
    w36,
    w33095,
    w16384,
    w49479,
    w9216,
    w8965,
    w576,
    w9541,
    w64,
    w315,
    w8192,
    w8507,
    w66264,
    w66519,
    w66511,
    w20160,
    w86679,
    w16064,
    w24347,
    w2048,
    w22299,
    w1020,
    w34115,
    w272920,
    w263379,
    w197916,
    w284595,
    w389552,
    w104957,
    w529520,
    w442841,
    w706220,
    w176555,
    w1004,
    w283591,
    w143440,
    w140151,
    w286880,
    w319975,
    w319974,
    w159987,
    w706475,
    w698192,
    w43637,
    w265056,
    w405207,
    w73728,
    w331479,
    w174548,
    w617389,
    w617704,
    w77213,
    w530112,
    w463601,
    w58394,
    w29197,
    w353110,
    w344827,
    w184693,
    w346716,
    w691543,
    w700050,
    w350025,
    w16,
    w691527,
    w810414,
    w118887,
    w184693_,
    w43637_,
    w152656,
    w152656_,
    w22299_,
    w159987_,
    w140151_,
    w154426,
    w49479_,
    w118887_,
    w58394_,
    w34028,
    w34028_,
    w173358,
    w173358_,
    w209914,
    w209914_,
    w132524,
    w264760;

  assign w1 = X;
  assign w256 = w1 << 8;
  assign w255 = w256 - w1;
  assign w4 = w1 << 2;
  assign w251 = w255 - w4;
  assign w8032 = w251 << 5;
  assign w8283 = w251 + w8032;
  assign w33132 = w8283 << 2;
  assign w33131 = w33132 - w1;
  assign w8 = w1 << 3;
  assign w9 = w1 + w8;
  assign w36 = w9 << 2;
  assign w33095 = w33131 - w36;
  assign w16384 = w1 << 14;
  assign w49479 = w33095 + w16384;
  assign w9216 = w9 << 10;
  assign w8965 = w9216 - w251;
  assign w576 = w9 << 6;
  assign w9541 = w8965 + w576;
  assign w64 = w1 << 6;
  assign w315 = w251 + w64;
  assign w8192 = w1 << 13;
  assign w8507 = w315 + w8192;
  assign w66264 = w8283 << 3;
  assign w66519 = w255 + w66264;
  assign w66511 = w66519 - w8;
  assign w20160 = w315 << 6;
  assign w86679 = w66519 + w20160;
  assign w16064 = w251 << 6;
  assign w24347 = w8283 + w16064;
  assign w2048 = w1 << 11;
  assign w22299 = w24347 - w2048;
  assign w1020 = w255 << 2;
  assign w34115 = w33095 + w1020;
  assign w272920 = w34115 << 3;
  assign w263379 = w272920 - w9541;
  assign w197916 = w49479 << 2;
  assign w284595 = w86679 + w197916;
  assign w389552 = w24347 << 4;
  assign w104957 = w389552 - w284595;
  assign w529520 = w33095 << 4;
  assign w442841 = w529520 - w86679;
  assign w706220 = w263379 + w442841;
  assign w176555 = w706220 >> 2;
  assign w1004 = w251 << 2;
  assign w283591 = w284595 - w1004;
  assign w143440 = w8965 << 4;
  assign w140151 = w283591 - w143440;
  assign w286880 = w8965 << 5;
  assign w319975 = w33095 + w286880;
  assign w319974 = w319975 - w1;
  assign w159987 = w319974 >> 1;
  assign w706475 = w255 + w706220;
  assign w698192 = w706475 - w8283;
  assign w43637 = w698192 >> 4;
  assign w265056 = w8283 << 5;
  assign w405207 = w140151 + w265056;
  assign w73728 = w9 << 13;
  assign w331479 = w405207 - w73728;
  assign w174548 = w43637 << 2;
  assign w617389 = w442841 + w174548;
  assign w617704 = w315 + w617389;
  assign w77213 = w617704 >> 3;
  assign w530112 = w8283 << 6;
  assign w463601 = w530112 - w66511;
  assign w58394 = w463601 - w405207;
  assign w29197 = w58394 >> 1;
  assign w353110 = w176555 << 1;
  assign w344827 = w353110 - w8283;
  assign w184693 = w529520 - w344827;
  assign w346716 = w86679 << 2;
  assign w691543 = w344827 + w346716;
  assign w700050 = w8507 + w691543;
  assign w350025 = w700050 >> 1;
  assign w16 = w1 << 4;
  assign w691527 = w691543 - w16;
  assign w810414 = w405207 << 1;
  assign w118887 = w810414 - w691527;
  assign w184693_ = -1 * w184693;
  assign w43637_ = -1 * w43637;
  assign w152656 = w9541 << 4;
  assign w152656_ = -1 * w152656;
  assign w22299_ = -1 * w22299;
  assign w159987_ = -1 * w159987;
  assign w140151_ = -1 * w140151;
  assign w154426 = w77213 << 1;
  assign w49479_ = -1 * w49479;
  assign w118887_ = -1 * w118887;
  assign w58394_ = -1 * w58394;
  assign w34028 = w8507 << 2;
  assign w34028_ = -1 * w34028;
  assign w173358 = w86679 << 1;
  assign w173358_ = -1 * w173358;
  assign w209914 = w104957 << 1;
  assign w209914_ = -1 * w209914;
  assign w132524 = w33131 << 2;
  assign w264760 = w33095 << 3;

  assign Y[0] = w350025[51:20];
  assign Y[1] = w184693_[51:20];
  assign Y[2] = w263379[51:20];
  assign Y[3] = w66511[51:20];
  assign Y[4] = w43637_[51:20];
  assign Y[5] = w152656_[51:20];
  assign Y[6] = w22299_[51:20];
  assign Y[7] = w159987_[51:20];
  assign Y[8] = w140151_[51:20];
  assign Y[9] = w154426[51:20];
  assign Y[10] = w49479_[51:20];
  assign Y[11] = w118887_[51:20];
  assign Y[12] = w331479[51:20];
  assign Y[13] = w58394_[51:20];
  assign Y[14] = w34028_[51:20];
  assign Y[15] = w173358_[51:20];
  assign Y[16] = w176555[51:20];
  assign Y[17] = w209914_[51:20];
  assign Y[18] = w132524[51:20];
  assign Y[19] = w264760[51:20];

endmodule //multiplier_block