/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r2 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [51:0]
    w1,
    w8192,
    w8191,
    w32,
    w33,
    w66,
    w67,
    w256,
    w223,
    w892,
    w9083,
    w4224,
    w4191,
    w33528,
    w33751,
    w16764,
    w16831,
    w134648,
    w142839,
    w264,
    w8455,
    w262112,
    w253657,
    w536,
    w7919,
    w33792,
    w25873,
    w65528,
    w73447,
    w327104,
    w5111,
    w3568,
    w1543,
    w790016,
    w790083,
    w789860,
    w197465,
    w131056,
    w384713,
    w380522,
    w190261,
    w185150,
    w92575,
    w88384,
    w1381,
    w135168,
    w42593,
    w581312,
    w623905,
    w654208,
    w30303,
    w587576,
    w444737,
    w64215,
    w540672,
    w350411,
    w67502,
    w282909,
    w484848,
    w484849,
    w201940,
    w50485,
    w100970,
    w101003,
    w8,
    w101011,
    w236171,
    w472342,
    w468151,
    w437848,
    w54731,
    w673887,
    w672506,
    w336253,
    w33751_,
    w146894,
    w146894_,
    w3086,
    w3086_,
    w253657_,
    w121212,
    w404044,
    w404044_,
    w18166,
    w22096,
    w109462,
    w1072,
    w1072_,
    w336253_,
    w403880,
    w403880_,
    w64215_;

  assign w1 = X;
  assign w8192 = w1 << 13;
  assign w8191 = w8192 - w1;
  assign w32 = w1 << 5;
  assign w33 = w1 + w32;
  assign w66 = w33 << 1;
  assign w67 = w1 + w66;
  assign w256 = w1 << 8;
  assign w223 = w256 - w33;
  assign w892 = w223 << 2;
  assign w9083 = w8191 + w892;
  assign w4224 = w33 << 7;
  assign w4191 = w4224 - w33;
  assign w33528 = w4191 << 3;
  assign w33751 = w223 + w33528;
  assign w16764 = w4191 << 2;
  assign w16831 = w67 + w16764;
  assign w134648 = w16831 << 3;
  assign w142839 = w8191 + w134648;
  assign w264 = w33 << 3;
  assign w8455 = w8191 + w264;
  assign w262112 = w8191 << 5;
  assign w253657 = w262112 - w8455;
  assign w536 = w67 << 3;
  assign w7919 = w8455 - w536;
  assign w33792 = w33 << 10;
  assign w25873 = w33792 - w7919;
  assign w65528 = w8191 << 3;
  assign w73447 = w7919 + w65528;
  assign w327104 = w253657 + w73447;
  assign w5111 = w327104 >> 6;
  assign w3568 = w223 << 4;
  assign w1543 = w5111 - w3568;
  assign w790016 = w1543 << 9;
  assign w790083 = w67 + w790016;
  assign w789860 = w790083 - w223;
  assign w197465 = w789860 >> 2;
  assign w131056 = w8191 << 4;
  assign w384713 = w253657 + w131056;
  assign w380522 = w384713 - w4191;
  assign w190261 = w380522 >> 1;
  assign w185150 = w190261 - w5111;
  assign w92575 = w185150 >> 1;
  assign w88384 = w92575 - w4191;
  assign w1381 = w88384 >> 6;
  assign w135168 = w33 << 12;
  assign w42593 = w135168 - w92575;
  assign w581312 = w9083 << 6;
  assign w623905 = w42593 + w581312;
  assign w654208 = w5111 << 7;
  assign w30303 = w654208 - w623905;
  assign w587576 = w73447 << 3;
  assign w444737 = w587576 - w142839;
  assign w64215 = w444737 - w380522;
  assign w540672 = w33 << 14;
  assign w350411 = w540672 - w190261;
  assign w67502 = w33751 << 1;
  assign w282909 = w350411 - w67502;
  assign w484848 = w30303 << 4;
  assign w484849 = w1 + w484848;
  assign w201940 = w484849 - w282909;
  assign w50485 = w201940 >> 2;
  assign w100970 = w50485 << 1;
  assign w101003 = w33 + w100970;
  assign w8 = w1 << 3;
  assign w101011 = w101003 + w8;
  assign w236171 = w101003 + w135168;
  assign w472342 = w236171 << 1;
  assign w468151 = w472342 - w4191;
  assign w437848 = w468151 - w30303;
  assign w54731 = w437848 >> 3;
  assign w673887 = w92575 + w581312;
  assign w672506 = w673887 - w1381;
  assign w336253 = w672506 >> 1;
  assign w33751_ = -1 * w33751;
  assign w146894 = w73447 << 1;
  assign w146894_ = -1 * w146894;
  assign w3086 = w1543 << 1;
  assign w3086_ = -1 * w3086;
  assign w253657_ = -1 * w253657;
  assign w121212 = w30303 << 2;
  assign w404044 = w101011 << 2;
  assign w404044_ = -1 * w404044;
  assign w18166 = w9083 << 1;
  assign w22096 = w1381 << 4;
  assign w109462 = w54731 << 1;
  assign w1072 = w67 << 4;
  assign w1072_ = -1 * w1072;
  assign w336253_ = -1 * w336253;
  assign w403880 = w50485 << 3;
  assign w403880_ = -1 * w403880;
  assign w64215_ = -1 * w64215;

  assign Y[0] = w236171[51:20];
  assign Y[1] = w33751_[51:20];
  assign Y[2] = w146894_[51:20];
  assign Y[3] = w282909[51:20];
  assign Y[4] = w190261[51:20];
  assign Y[5] = w3086_[51:20];
  assign Y[6] = w197465[51:20];
  assign Y[7] = w253657_[51:20];
  assign Y[8] = w121212[51:20];
  assign Y[9] = w42593[51:20];
  assign Y[10] = w142839[51:20];
  assign Y[11] = w404044_[51:20];
  assign Y[12] = w18166[51:20];
  assign Y[13] = w22096[51:20];
  assign Y[14] = w109462[51:20];
  assign Y[15] = w25873[51:20];
  assign Y[16] = w1072_[51:20];
  assign Y[17] = w336253_[51:20];
  assign Y[18] = w403880_[51:20];
  assign Y[19] = w64215_[51:20];

endmodule //multiplier_block