/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r8 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [51:0]
    w1,
    w8,
    w7,
    w14336,
    w14343,
    w56,
    w14287,
    w256,
    w257,
    w4112,
    w18455,
    w1028,
    w19483,
    w896,
    w18587,
    w32,
    w25,
    w57372,
    w57397,
    w2056,
    w59453,
    w45117,
    w295280,
    w295281,
    w51200,
    w244081,
    w311728,
    w292245,
    w28574,
    w320819,
    w102400,
    w423219,
    w457184,
    w33965,
    w512,
    w243569,
    w14,
    w243555,
    w131584,
    w426865,
    w183296,
    w179,
    w2864,
    w21451,
    w6400,
    w15051,
    w85804,
    w104259,
    w721872,
    w687907,
    w733184,
    w45277,
    w65536,
    w488755,
    w534032,
    w33377,
    w64,
    w320755,
    w76674,
    w38337,
    w426833,
    w115105,
    w50,
    w320869,
    w302414,
    w151207,
    w448,
    w427281,
    w441568,
    w13799,
    w114744,
    w603499,
    w237812,
    w365687,
    w28686,
    w122521,
    w104066,
    w52033,
    w147640,
    w147640_,
    w306696,
    w230210,
    w243555_,
    w120408,
    w120408_,
    w181108,
    w151207_,
    w228592,
    w110392,
    w135860,
    w135860_,
    w416264,
    w90234,
    w90234_,
    w297392,
    w297392_,
    w33377_,
    w5728,
    w104259_,
    w365687_;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w7 = w8 - w1;
  assign w14336 = w7 << 11;
  assign w14343 = w7 + w14336;
  assign w56 = w7 << 3;
  assign w14287 = w14343 - w56;
  assign w256 = w1 << 8;
  assign w257 = w1 + w256;
  assign w4112 = w257 << 4;
  assign w18455 = w14343 + w4112;
  assign w1028 = w257 << 2;
  assign w19483 = w18455 + w1028;
  assign w896 = w7 << 7;
  assign w18587 = w19483 - w896;
  assign w32 = w1 << 5;
  assign w25 = w32 - w7;
  assign w57372 = w14343 << 2;
  assign w57397 = w25 + w57372;
  assign w2056 = w257 << 3;
  assign w59453 = w57397 + w2056;
  assign w45117 = w59453 - w14336;
  assign w295280 = w18455 << 4;
  assign w295281 = w1 + w295280;
  assign w51200 = w25 << 11;
  assign w244081 = w295281 - w51200;
  assign w311728 = w19483 << 4;
  assign w292245 = w311728 - w19483;
  assign w28574 = w14287 << 1;
  assign w320819 = w292245 + w28574;
  assign w102400 = w25 << 12;
  assign w423219 = w320819 + w102400;
  assign w457184 = w14287 << 5;
  assign w33965 = w457184 - w423219;
  assign w512 = w1 << 9;
  assign w243569 = w244081 - w512;
  assign w14 = w7 << 1;
  assign w243555 = w243569 - w14;
  assign w131584 = w257 << 9;
  assign w426865 = w295281 + w131584;
  assign w183296 = w426865 - w243569;
  assign w179 = w183296 >> 10;
  assign w2864 = w179 << 4;
  assign w21451 = w18587 + w2864;
  assign w6400 = w25 << 8;
  assign w15051 = w21451 - w6400;
  assign w85804 = w21451 << 2;
  assign w104259 = w18455 + w85804;
  assign w721872 = w45117 << 4;
  assign w687907 = w721872 - w33965;
  assign w733184 = w179 << 12;
  assign w45277 = w733184 - w687907;
  assign w65536 = w1 << 16;
  assign w488755 = w423219 + w65536;
  assign w534032 = w45277 + w488755;
  assign w33377 = w534032 >> 4;
  assign w64 = w1 << 6;
  assign w320755 = w320819 - w64;
  assign w76674 = w320755 - w244081;
  assign w38337 = w76674 >> 1;
  assign w426833 = w426865 - w32;
  assign w115105 = w426833 - w311728;
  assign w50 = w25 << 1;
  assign w320869 = w320819 + w50;
  assign w302414 = w320869 - w18455;
  assign w151207 = w302414 >> 1;
  assign w448 = w7 << 6;
  assign w427281 = w426833 + w448;
  assign w441568 = w14287 + w427281;
  assign w13799 = w441568 >> 5;
  assign w114744 = w14343 << 3;
  assign w603499 = w488755 + w114744;
  assign w237812 = w59453 << 2;
  assign w365687 = w603499 - w237812;
  assign w28686 = w14343 << 1;
  assign w122521 = w151207 - w28686;
  assign w104066 = w122521 - w18455;
  assign w52033 = w104066 >> 1;
  assign w147640 = w18455 << 3;
  assign w147640_ = -1 * w147640;
  assign w306696 = w38337 << 3;
  assign w230210 = w115105 << 1;
  assign w243555_ = -1 * w243555;
  assign w120408 = w15051 << 3;
  assign w120408_ = -1 * w120408;
  assign w181108 = w45277 << 2;
  assign w151207_ = -1 * w151207;
  assign w228592 = w14287 << 4;
  assign w110392 = w13799 << 3;
  assign w135860 = w33965 << 2;
  assign w135860_ = -1 * w135860;
  assign w416264 = w52033 << 3;
  assign w90234 = w45117 << 1;
  assign w90234_ = -1 * w90234;
  assign w297392 = w18587 << 4;
  assign w297392_ = -1 * w297392;
  assign w33377_ = -1 * w33377;
  assign w5728 = w179 << 5;
  assign w104259_ = -1 * w104259;
  assign w365687_ = -1 * w365687;

  assign Y[0] = w147640_[51:20];
  assign Y[1] = w306696[51:20];
  assign Y[2] = w230210[51:20];
  assign Y[3] = w243555_[51:20];
  assign Y[4] = w120408_[51:20];
  assign Y[5] = w181108[51:20];
  assign Y[6] = w151207_[51:20];
  assign Y[7] = w228592[51:20];
  assign Y[8] = w110392[51:20];
  assign Y[9] = w135860_[51:20];
  assign Y[10] = w416264[51:20];
  assign Y[11] = w320819[51:20];
  assign Y[12] = w90234_[51:20];
  assign Y[13] = w297392_[51:20];
  assign Y[14] = w33377_[51:20];
  assign Y[15] = w244081[51:20];
  assign Y[16] = w5728[51:20];
  assign Y[17] = w104259_[51:20];
  assign Y[18] = w57397[51:20];
  assign Y[19] = w365687_[51:20];

endmodule //multiplier_block