/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r7 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [51:0]
    w1,
    w64,
    w63,
    w8,
    w55,
    w1024,
    w969,
    w62016,
    w62017,
    w128,
    w191,
    w6112,
    w6057,
    w15504,
    w16473,
    w3056,
    w13417,
    w16128,
    w32601,
    w1008,
    w1071,
    w14080,
    w13009,
    w8192,
    w24665,
    w25689,
    w53668,
    w29003,
    w2,
    w29005,
    w129024,
    w158027,
    w260808,
    w260617,
    w524288,
    w263671,
    w214672,
    w478343,
    w320316,
    w80079,
    w316054,
    w162289,
    w1042468,
    w1042469,
    w901120,
    w141349,
    w956686,
    w956685,
    w928096,
    w28589,
    w496128,
    w235511,
    w297527,
    w516096,
    w487093,
    w567172,
    w141793,
    w32768,
    w454325,
    w428636,
    w107159,
    w31008,
    w456085,
    w195468,
    w48867,
    w324578,
    w291977,
    w96509,
    w24228,
    w166021,
    w112353,
    w225280,
    w366629,
    w449412,
    w82783,
    w57178,
    w57178_,
    w165566,
    w282698,
    w141793_,
    w102756,
    w102756_,
    w97734,
    w97734_,
    w48456,
    w48456_,
    w224706,
    w224706_,
    w96509_,
    w130404,
    w80079_,
    w248068,
    w26834,
    w26834_,
    w158027_;

  assign w1 = X;
  assign w64 = w1 << 6;
  assign w63 = w64 - w1;
  assign w8 = w1 << 3;
  assign w55 = w63 - w8;
  assign w1024 = w1 << 10;
  assign w969 = w1024 - w55;
  assign w62016 = w969 << 6;
  assign w62017 = w1 + w62016;
  assign w128 = w1 << 7;
  assign w191 = w63 + w128;
  assign w6112 = w191 << 5;
  assign w6057 = w6112 - w55;
  assign w15504 = w969 << 4;
  assign w16473 = w969 + w15504;
  assign w3056 = w191 << 4;
  assign w13417 = w16473 - w3056;
  assign w16128 = w63 << 8;
  assign w32601 = w16473 + w16128;
  assign w1008 = w63 << 4;
  assign w1071 = w63 + w1008;
  assign w14080 = w55 << 8;
  assign w13009 = w14080 - w1071;
  assign w8192 = w1 << 13;
  assign w24665 = w16473 + w8192;
  assign w25689 = w24665 + w1024;
  assign w53668 = w13417 << 2;
  assign w29003 = w53668 - w24665;
  assign w2 = w1 << 1;
  assign w29005 = w29003 + w2;
  assign w129024 = w63 << 11;
  assign w158027 = w29003 + w129024;
  assign w260808 = w32601 << 3;
  assign w260617 = w260808 - w191;
  assign w524288 = w1 << 19;
  assign w263671 = w524288 - w260617;
  assign w214672 = w13417 << 4;
  assign w478343 = w263671 + w214672;
  assign w320316 = w478343 - w158027;
  assign w80079 = w320316 >> 2;
  assign w316054 = w158027 << 1;
  assign w162289 = w478343 - w316054;
  assign w1042468 = w260617 << 2;
  assign w1042469 = w1 + w1042468;
  assign w901120 = w55 << 14;
  assign w141349 = w1042469 - w901120;
  assign w956686 = w478343 << 1;
  assign w956685 = w956686 - w1;
  assign w928096 = w29003 << 5;
  assign w28589 = w956685 - w928096;
  assign w496128 = w969 << 9;
  assign w235511 = w496128 - w260617;
  assign w297527 = w235511 + w62016;
  assign w516096 = w63 << 13;
  assign w487093 = w516096 - w29003;
  assign w567172 = w80079 + w487093;
  assign w141793 = w567172 >> 2;
  assign w32768 = w1 << 15;
  assign w454325 = w487093 - w32768;
  assign w428636 = w454325 - w25689;
  assign w107159 = w428636 >> 2;
  assign w31008 = w969 << 5;
  assign w456085 = w487093 - w31008;
  assign w195468 = w456085 - w260617;
  assign w48867 = w195468 >> 2;
  assign w324578 = w162289 << 1;
  assign w291977 = w324578 - w32601;
  assign w96509 = w291977 - w195468;
  assign w24228 = w6057 << 2;
  assign w166021 = w141793 + w24228;
  assign w112353 = w166021 - w53668;
  assign w225280 = w55 << 12;
  assign w366629 = w141349 + w225280;
  assign w449412 = w112353 << 2;
  assign w82783 = w449412 - w366629;
  assign w57178 = w28589 << 1;
  assign w57178_ = -1 * w57178;
  assign w165566 = w82783 << 1;
  assign w282698 = w141349 << 1;
  assign w141793_ = -1 * w141793;
  assign w102756 = w25689 << 2;
  assign w102756_ = -1 * w102756;
  assign w97734 = w48867 << 1;
  assign w97734_ = -1 * w97734;
  assign w48456 = w6057 << 3;
  assign w48456_ = -1 * w48456;
  assign w224706 = w112353 << 1;
  assign w224706_ = -1 * w224706;
  assign w96509_ = -1 * w96509;
  assign w130404 = w32601 << 2;
  assign w80079_ = -1 * w80079;
  assign w248068 = w62017 << 2;
  assign w26834 = w13417 << 1;
  assign w26834_ = -1 * w26834;
  assign w158027_ = -1 * w158027;

  assign Y[0] = w57178_[51:20];
  assign Y[1] = w165566[51:20];
  assign Y[2] = w282698[51:20];
  assign Y[3] = w263671[51:20];
  assign Y[4] = w29005[51:20];
  assign Y[5] = w141793_[51:20];
  assign Y[6] = w102756_[51:20];
  assign Y[7] = w162289[51:20];
  assign Y[8] = w97734_[51:20];
  assign Y[9] = w48456_[51:20];
  assign Y[10] = w224706_[51:20];
  assign Y[11] = w96509_[51:20];
  assign Y[12] = w130404[51:20];
  assign Y[13] = w80079_[51:20];
  assign Y[14] = w13009[51:20];
  assign Y[15] = w107159[51:20];
  assign Y[16] = w297527[51:20];
  assign Y[17] = w248068[51:20];
  assign Y[18] = w26834_[51:20];
  assign Y[19] = w158027_[51:20];

endmodule //multiplier_block

