/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r18 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [51:0]
    w1,
    w8,
    w9,
    w64,
    w55,
    w4,
    w51,
    w816,
    w761,
    w73,
    w7040,
    w6967,
    w584,
    w657,
    w42048,
    w42103,
    w74752,
    w75409,
    w13056,
    w13713,
    w3520,
    w10193,
    w102,
    w13611,
    w880,
    w881,
    w56384,
    w56333,
    w81544,
    w80663,
    w36,
    w91,
    w28192,
    w28283,
    w46592,
    w32879,
    w20386,
    w12493,
    w10512,
    w43391,
    w86782,
    w86781,
    w100393,
    w194816,
    w281597,
    w181204,
    w45301,
    w336384,
    w249603,
    w161326,
    w88277,
    w799552,
    w549949,
    w549898,
    w274949,
    w499206,
    w498325,
    w11648,
    w509973,
    w112640,
    w213033,
    w301310,
    w150655,
    w65758,
    w575731,
    w450560,
    w125171,
    w6528,
    w6528_,
    w347124,
    w113132,
    w42103_,
    w49972,
    w263032,
    w263032_,
    w1522,
    w1522_,
    w55736,
    w353108,
    w150818,
    w200786,
    w200786_,
    w90602,
    w163088,
    w112666,
    w161326_;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w9 = w1 + w8;
  assign w64 = w1 << 6;
  assign w55 = w64 - w9;
  assign w4 = w1 << 2;
  assign w51 = w55 - w4;
  assign w816 = w51 << 4;
  assign w761 = w816 - w55;
  assign w73 = w9 + w64;
  assign w7040 = w55 << 7;
  assign w6967 = w7040 - w73;
  assign w584 = w73 << 3;
  assign w657 = w73 + w584;
  assign w42048 = w657 << 6;
  assign w42103 = w55 + w42048;
  assign w74752 = w73 << 10;
  assign w75409 = w657 + w74752;
  assign w13056 = w51 << 8;
  assign w13713 = w657 + w13056;
  assign w3520 = w55 << 6;
  assign w10193 = w13713 - w3520;
  assign w102 = w51 << 1;
  assign w13611 = w13713 - w102;
  assign w880 = w55 << 4;
  assign w881 = w1 + w880;
  assign w56384 = w881 << 6;
  assign w56333 = w56384 - w51;
  assign w81544 = w10193 << 3;
  assign w80663 = w81544 - w881;
  assign w36 = w9 << 2;
  assign w91 = w55 + w36;
  assign w28192 = w881 << 5;
  assign w28283 = w91 + w28192;
  assign w46592 = w91 << 9;
  assign w32879 = w46592 - w13713;
  assign w20386 = w10193 << 1;
  assign w12493 = w32879 - w20386;
  assign w10512 = w657 << 4;
  assign w43391 = w32879 + w10512;
  assign w86782 = w43391 << 1;
  assign w86781 = w86782 - w1;
  assign w100393 = w13611 + w86782;
  assign w194816 = w761 << 8;
  assign w281597 = w86781 + w194816;
  assign w181204 = w281597 - w100393;
  assign w45301 = w181204 >> 2;
  assign w336384 = w657 << 9;
  assign w249603 = w336384 - w86781;
  assign w161326 = w80663 << 1;
  assign w88277 = w249603 - w161326;
  assign w799552 = w12493 << 6;
  assign w549949 = w799552 - w249603;
  assign w549898 = w549949 - w51;
  assign w274949 = w549898 >> 1;
  assign w499206 = w249603 << 1;
  assign w498325 = w499206 - w881;
  assign w11648 = w91 << 7;
  assign w509973 = w498325 + w11648;
  assign w112640 = w55 << 11;
  assign w213033 = w100393 + w112640;
  assign w301310 = w88277 + w213033;
  assign w150655 = w301310 >> 1;
  assign w65758 = w32879 << 1;
  assign w575731 = w509973 + w65758;
  assign w450560 = w55 << 13;
  assign w125171 = w575731 - w450560;
  assign w6528 = w51 << 7;
  assign w6528_ = -1 * w6528;
  assign w347124 = w86781 << 2;
  assign w113132 = w28283 << 2;
  assign w42103_ = -1 * w42103;
  assign w49972 = w12493 << 2;
  assign w263032 = w32879 << 3;
  assign w263032_ = -1 * w263032;
  assign w1522 = w761 << 1;
  assign w1522_ = -1 * w1522;
  assign w55736 = w6967 << 3;
  assign w353108 = w88277 << 2;
  assign w150818 = w75409 << 1;
  assign w200786 = w100393 << 1;
  assign w200786_ = -1 * w200786;
  assign w90602 = w45301 << 1;
  assign w163088 = w10193 << 4;
  assign w112666 = w56333 << 1;
  assign w161326_ = -1 * w161326;

  assign Y[0] = w13611[51:20];
  assign Y[1] = w6528_[51:20];
  assign Y[2] = w347124[51:20];
  assign Y[3] = w113132[51:20];
  assign Y[4] = w150655[51:20];
  assign Y[5] = w274949[51:20];
  assign Y[6] = w42103_[51:20];
  assign Y[7] = w49972[51:20];
  assign Y[8] = w263032_[51:20];
  assign Y[9] = w1522_[51:20];
  assign Y[10] = w55736[51:20];
  assign Y[11] = w353108[51:20];
  assign Y[12] = w150818[51:20];
  assign Y[13] = w200786_[51:20];
  assign Y[14] = w90602[51:20];
  assign Y[15] = w163088[51:20];
  assign Y[16] = w112666[51:20];
  assign Y[17] = w509973[51:20];
  assign Y[18] = w161326_[51:20];
  assign Y[19] = w125171[51:20];

endmodule //multiplier_block
