/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r0 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [51:0]
    w1,
    w8,
    w9,
    w32768,
    w32767,
    w9216,
    w23551,
    w64,
    w32831,
    w32,
    w41,
    w1312,
    w1353,
    w164,
    w205,
    w26240,
    w2689,
    w1024,
    w1023,
    w4092,
    w19459,
    w209920,
    w208897,
    w104960,
    w104969,
    w104970,
    w52485,
    w2624,
    w107593,
    w2048,
    w2253,
    w4506,
    w19045,
    w144192,
    w249161,
    w72,
    w1095,
    w4380,
    w2127,
    w70080,
    w70121,
    w131068,
    w339965,
    w311344,
    w28621,
    w17016,
    w356981,
    w355628,
    w88907,
    w228968,
    w228969,
    w231658,
    w115829,
    w86048,
    w335209,
    w262144,
    w73065,
    w298827,
    w36382,
    w18191,
    w294912,
    w297601,
    w224536,
    w28067,
    w262648,
    w262657,
    w209940,
    w52717,
    w145528,
    w145519,
    w117138,
    w58569,
    w115829_,
    w249161_,
    w146130,
    w146130_,
    w215186,
    w215186_,
    w1353_,
    w105434,
    w105434_,
    w112268,
    w112268_,
    w5378,
    w5378_,
    w65662,
    w140242,
    w72764,
    w72764_,
    w228968_,
    w152360,
    w152360_,
    w177814;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w9 = w1 + w8;
  assign w32768 = w1 << 15;
  assign w32767 = w32768 - w1;
  assign w9216 = w9 << 10;
  assign w23551 = w32767 - w9216;
  assign w64 = w1 << 6;
  assign w32831 = w32767 + w64;
  assign w32 = w1 << 5;
  assign w41 = w9 + w32;
  assign w1312 = w41 << 5;
  assign w1353 = w41 + w1312;
  assign w164 = w41 << 2;
  assign w205 = w41 + w164;
  assign w26240 = w205 << 7;
  assign w2689 = w26240 - w23551;
  assign w1024 = w1 << 10;
  assign w1023 = w1024 - w1;
  assign w4092 = w1023 << 2;
  assign w19459 = w23551 - w4092;
  assign w209920 = w205 << 10;
  assign w208897 = w209920 - w1023;
  assign w104960 = w205 << 9;
  assign w104969 = w9 + w104960;
  assign w104970 = w1 + w104969;
  assign w52485 = w104970 >> 1;
  assign w2624 = w41 << 6;
  assign w107593 = w104969 + w2624;
  assign w2048 = w1 << 11;
  assign w2253 = w205 + w2048;
  assign w4506 = w2253 << 1;
  assign w19045 = w23551 - w4506;
  assign w144192 = w2253 << 6;
  assign w249161 = w104969 + w144192;
  assign w72 = w9 << 3;
  assign w1095 = w1023 + w72;
  assign w4380 = w1095 << 2;
  assign w2127 = w4380 - w2253;
  assign w70080 = w1095 << 6;
  assign w70121 = w41 + w70080;
  assign w131068 = w32767 << 2;
  assign w339965 = w208897 + w131068;
  assign w311344 = w19459 << 4;
  assign w28621 = w339965 - w311344;
  assign w17016 = w2127 << 3;
  assign w356981 = w339965 + w17016;
  assign w355628 = w356981 - w1353;
  assign w88907 = w355628 >> 2;
  assign w228968 = w28621 << 3;
  assign w228969 = w1 + w228968;
  assign w231658 = w2689 + w228969;
  assign w115829 = w231658 >> 1;
  assign w86048 = w2689 << 5;
  assign w335209 = w249161 + w86048;
  assign w262144 = w1 << 18;
  assign w73065 = w335209 - w262144;
  assign w298827 = w88907 + w209920;
  assign w36382 = w335209 - w298827;
  assign w18191 = w36382 >> 1;
  assign w294912 = w9 << 15;
  assign w297601 = w2689 + w294912;
  assign w224536 = w297601 - w73065;
  assign w28067 = w224536 >> 3;
  assign w262648 = w32831 << 3;
  assign w262657 = w9 + w262648;
  assign w209940 = w52485 << 2;
  assign w52717 = w262657 - w209940;
  assign w145528 = w18191 << 3;
  assign w145519 = w145528 - w9;
  assign w117138 = w262657 - w145519;
  assign w58569 = w117138 >> 1;
  assign w115829_ = -1 * w115829;
  assign w249161_ = -1 * w249161;
  assign w146130 = w73065 << 1;
  assign w146130_ = -1 * w146130;
  assign w215186 = w107593 << 1;
  assign w215186_ = -1 * w215186;
  assign w1353_ = -1 * w1353;
  assign w105434 = w52717 << 1;
  assign w105434_ = -1 * w105434;
  assign w112268 = w28067 << 2;
  assign w112268_ = -1 * w112268;
  assign w5378 = w2689 << 1;
  assign w5378_ = -1 * w5378;
  assign w65662 = w32831 << 1;
  assign w140242 = w70121 << 1;
  assign w72764 = w18191 << 2;
  assign w72764_ = -1 * w72764;
  assign w228968_ = -1 * w228968;
  assign w152360 = w19045 << 3;
  assign w152360_ = -1 * w152360;
  assign w177814 = w88907 << 1;

  assign Y[0] = w208897[51:20];
  assign Y[1] = w115829_[51:20];
  assign Y[2] = w249161_[51:20];
  assign Y[3] = w19459[51:20];
  assign Y[4] = w146130_[51:20];
  assign Y[5] = w215186_[51:20];
  assign Y[6] = w1353_[51:20];
  assign Y[7] = w105434_[51:20];
  assign Y[8] = w2127[51:20];
  assign Y[9] = w112268_[51:20];
  assign Y[10] = w58569[51:20];
  assign Y[11] = w5378_[51:20];
  assign Y[12] = w65662[51:20];
  assign Y[13] = w140242[51:20];
  assign Y[14] = w52485[51:20];
  assign Y[15] = w72764_[51:20];
  assign Y[16] = w228968_[51:20];
  assign Y[17] = w23551[51:20];
  assign Y[18] = w152360_[51:20];
  assign Y[19] = w177814[51:20];

endmodule //multiplier_block
