
/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r17 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [51:0]
    w1,
    w4,
    w5,
    w20,
    w25,
    w80,
    w81,
    w2560,
    w2479,
    w5184,
    w5183,
    w5209,
    w320,
    w5529,
    w6400,
    w11609,
    w2,
    w5531,
    w640,
    w4891,
    w11062,
    w5879,
    w160,
    w241,
    w61696,
    w61721,
    w246884,
    w246885,
    w10,
    w246895,
    w47032,
    w293927,
    w165888,
    w128039,
    w493568,
    w499447,
    w131072,
    w368375,
    w256078,
    w255997,
    w9916,
    w246081,
    w511994,
    w511999,
    w506816,
    w7919,
    w331776,
    w326593,
    w32666,
    w16333,
    w493770,
    w555491,
    w299494,
    w149747,
    w39664,
    w595155,
    w707968,
    w112813,
    w331712,
    w444525,
    w451252,
    w6727,
    w626048,
    w626043,
    w653186,
    w27143,
    w163840,
    w130087,
    w191808,
    w2997,
    w50,
    w326543,
    w333376,
    w6833,
    w78256,
    w78256_,
    w20732,
    w19832,
    w92872,
    w47032_,
    w54286,
    w54286_,
    w44232,
    w130664,
    w51200,
    w112813_,
    w109328,
    w368375_,
    w31676,
    w31676_;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w5 = w1 + w4;
  assign w20 = w5 << 2;
  assign w25 = w5 + w20;
  assign w80 = w5 << 4;
  assign w81 = w1 + w80;
  assign w2560 = w5 << 9;
  assign w2479 = w2560 - w81;
  assign w5184 = w81 << 6;
  assign w5183 = w5184 - w1;
  assign w5209 = w25 + w5184;
  assign w320 = w5 << 6;
  assign w5529 = w5209 + w320;
  assign w6400 = w25 << 8;
  assign w11609 = w5209 + w6400;
  assign w2 = w1 << 1;
  assign w5531 = w5529 + w2;
  assign w640 = w5 << 7;
  assign w4891 = w5531 - w640;
  assign w11062 = w5531 << 1;
  assign w5879 = w11062 - w5183;
  assign w160 = w5 << 5;
  assign w241 = w81 + w160;
  assign w61696 = w241 << 8;
  assign w61721 = w25 + w61696;
  assign w246884 = w61721 << 2;
  assign w246885 = w1 + w246884;
  assign w10 = w5 << 1;
  assign w246895 = w246885 + w10;
  assign w47032 = w5879 << 3;
  assign w293927 = w246895 + w47032;
  assign w165888 = w81 << 11;
  assign w128039 = w293927 - w165888;
  assign w493568 = w241 << 11;
  assign w499447 = w5879 + w493568;
  assign w131072 = w1 << 17;
  assign w368375 = w499447 - w131072;
  assign w256078 = w128039 << 1;
  assign w255997 = w256078 - w81;
  assign w9916 = w2479 << 2;
  assign w246081 = w255997 - w9916;
  assign w511994 = w255997 << 1;
  assign w511999 = w5 + w511994;
  assign w506816 = w511999 - w5183;
  assign w7919 = w506816 >> 6;
  assign w331776 = w81 << 12;
  assign w326593 = w331776 - w5183;
  assign w32666 = w326593 - w293927;
  assign w16333 = w32666 >> 1;
  assign w493770 = w246885 << 1;
  assign w555491 = w61721 + w493770;
  assign w299494 = w555491 - w255997;
  assign w149747 = w299494 >> 1;
  assign w39664 = w2479 << 4;
  assign w595155 = w555491 + w39664;
  assign w707968 = w5531 << 7;
  assign w112813 = w707968 - w595155;
  assign w331712 = w5183 << 6;
  assign w444525 = w112813 + w331712;
  assign w451252 = w112813 << 2;
  assign w6727 = w451252 - w444525;
  assign w626048 = w4891 << 7;
  assign w626043 = w626048 - w5;
  assign w653186 = w326593 << 1;
  assign w27143 = w653186 - w626043;
  assign w163840 = w5 << 15;
  assign w130087 = w293927 - w163840;
  assign w191808 = w61721 + w130087;
  assign w2997 = w191808 >> 6;
  assign w50 = w25 << 1;
  assign w326543 = w326593 - w50;
  assign w333376 = w5209 << 6;
  assign w6833 = w333376 - w326543;
  assign w78256 = w4891 << 4;
  assign w78256_ = -1 * w78256;
  assign w20732 = w5183 << 2;
  assign w19832 = w2479 << 3;
  assign w92872 = w11609 << 3;
  assign w47032_ = -1 * w47032;
  assign w54286 = w27143 << 1;
  assign w54286_ = -1 * w54286;
  assign w44232 = w5529 << 3;
  assign w130664 = w16333 << 3;
  assign w51200 = w25 << 11;
  assign w112813_ = -1 * w112813;
  assign w109328 = w6833 << 4;
  assign w368375_ = -1 * w368375;
  assign w31676 = w7919 << 2;
  assign w31676_ = -1 * w31676;

  assign Y[0] = w246895[51:20];
  assign Y[1] = w78256_[51:20];
  assign Y[2] = w20732[51:20];
  assign Y[3] = w61721[51:20];
  assign Y[4] = w149747[51:20];
  assign Y[5] = w19832[51:20];
  assign Y[6] = w92872[51:20];
  assign Y[7] = w47032_[51:20];
  assign Y[8] = w6727[51:20];
  assign Y[9] = w54286_[51:20];
  assign Y[10] = w246081[51:20];
  assign Y[11] = w191808[51:20];
  assign Y[12] = w128039[51:20];
  assign Y[13] = w44232[51:20];
  assign Y[14] = w130664[51:20];
  assign Y[15] = w51200[51:20];
  assign Y[16] = w112813_[51:20];
  assign Y[17] = w109328[51:20];
  assign Y[18] = w368375_[51:20];
  assign Y[19] = w31676_[51:20];

endmodule //multiplier_block
