/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r0 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w32,
    w33,
    w4,
    w3,
    w16,
    w19,
    w24,
    w21,
    w48,
    w51,
    w768,
    w735,
    w2048,
    w2051,
    w256,
    w205,
    w672,
    w877,
    w38,
    w915,
    w512,
    w1389,
    w132,
    w111,
    w1536,
    w1647,
    w222,
    w2273,
    w3508,
    w3619,
    w7104,
    w7155,
    w657,
    w1024,
    w1681,
    w1314,
    w2191,
    w2940,
    w2283,
    w384,
    w385,
    w3893,
    w3080,
    w4761,
    w6528,
    w3619_,
    w7786,
    w7786_,
    w608,
    w4566,
    w4566_,
    w6724,
    w6724_,
    w42,
    w42_,
    w3294,
    w3294_,
    w66,
    w3508_,
    w1830,
    w168,
    w168_,
    w4382,
    w1640,
    w2273_,
    w7155_,
    w4761_,
    w5556;

  assign w1 = X;
  assign w32 = w1 << 5;
  assign w33 = w1 + w32;
  assign w4 = w1 << 2;
  assign w3 = w4 - w1;
  assign w16 = w1 << 4;
  assign w19 = w3 + w16;
  assign w24 = w3 << 3;
  assign w21 = w24 - w3;
  assign w48 = w3 << 4;
  assign w51 = w3 + w48;
  assign w768 = w3 << 8;
  assign w735 = w768 - w33;
  assign w2048 = w1 << 11;
  assign w2051 = w3 + w2048;
  assign w256 = w1 << 8;
  assign w205 = w256 - w51;
  assign w672 = w21 << 5;
  assign w877 = w205 + w672;
  assign w38 = w19 << 1;
  assign w915 = w877 + w38;
  assign w512 = w1 << 9;
  assign w1389 = w877 + w512;
  assign w132 = w33 << 2;
  assign w111 = w132 - w21;
  assign w1536 = w3 << 9;
  assign w1647 = w111 + w1536;
  assign w222 = w111 << 1;
  assign w2273 = w2051 + w222;
  assign w3508 = w877 << 2;
  assign w3619 = w111 + w3508;
  assign w7104 = w111 << 6;
  assign w7155 = w51 + w7104;
  assign w657 = w768 - w111;
  assign w1024 = w1 << 10;
  assign w1681 = w657 + w1024;
  assign w1314 = w657 << 1;
  assign w2191 = w877 + w1314;
  assign w2940 = w735 << 2;
  assign w2283 = w2940 - w657;
  assign w384 = w3 << 7;
  assign w385 = w1 + w384;
  assign w3893 = w385 + w3508;
  assign w3080 = w385 << 3;
  assign w4761 = w1681 + w3080;
  assign w6528 = w51 << 7;
  assign w3619_ = -1 * w3619;
  assign w7786 = w3893 << 1;
  assign w7786_ = -1 * w7786;
  assign w608 = w19 << 5;
  assign w4566 = w2283 << 1;
  assign w4566_ = -1 * w4566;
  assign w6724 = w1681 << 2;
  assign w6724_ = -1 * w6724;
  assign w42 = w21 << 1;
  assign w42_ = -1 * w42;
  assign w3294 = w1647 << 1;
  assign w3294_ = -1 * w3294;
  assign w66 = w33 << 1;
  assign w3508_ = -1 * w3508;
  assign w1830 = w915 << 1;
  assign w168 = w21 << 3;
  assign w168_ = -1 * w168;
  assign w4382 = w2191 << 1;
  assign w1640 = w205 << 3;
  assign w2273_ = -1 * w2273;
  assign w7155_ = -1 * w7155;
  assign w4761_ = -1 * w4761;
  assign w5556 = w1389 << 2;

  assign Y[0] = w6528[46:15];
  assign Y[1] = w3619_[46:15];
  assign Y[2] = w7786_[46:15];
  assign Y[3] = w608[46:15];
  assign Y[4] = w4566_[46:15];
  assign Y[5] = w6724_[46:15];
  assign Y[6] = w42_[46:15];
  assign Y[7] = w3294_[46:15];
  assign Y[8] = w66[46:15];
  assign Y[9] = w3508_[46:15];
  assign Y[10] = w1830[46:15];
  assign Y[11] = w168_[46:15];
  assign Y[12] = w2051[46:15];
  assign Y[13] = w4382[46:15];
  assign Y[14] = w1640[46:15];
  assign Y[15] = w2273_[46:15];
  assign Y[16] = w7155_[46:15];
  assign Y[17] = w735[46:15];
  assign Y[18] = w4761_[46:15];
  assign Y[19] = w5556[46:15];

endmodule //multiplier_block
