/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r19 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w64,
    w65,
    w512,
    w577,
    w2080,
    w1503,
    w4096,
    w2593,
    w4,
    w5,
    w160,
    w155,
    w320,
    w1183,
    w620,
    w43,
    w5120,
    w6303,
    w640,
    w639,
    w256,
    w383,
    w794,
    w397,
    w8,
    w631,
    w10224,
    w10801,
    w1240,
    w263,
    w688,
    w425,
    w2104,
    w4199,
    w5504,
    w5241,
    w3943,
    w8398,
    w8781,
    w2366,
    w227,
    w2048,
    w1821,
    w4208,
    w3981,
    w1816,
    w4487,
    w17562,
    w17557,
    w17492,
    w4373,
    w766,
    w766_,
    w3943_,
    w397_,
    w2480,
    w2480_,
    w3006,
    w8781_,
    w2752,
    w1262,
    w10801_,
    w3642,
    w3642_,
    w8398_,
    w6303_,
    w10372,
    w10372_,
    w850,
    w850_,
    w4616,
    w4616_;

  assign w1 = X;
  assign w64 = w1 << 6;
  assign w65 = w1 + w64;
  assign w512 = w1 << 9;
  assign w577 = w65 + w512;
  assign w2080 = w65 << 5;
  assign w1503 = w2080 - w577;
  assign w4096 = w1 << 12;
  assign w2593 = w4096 - w1503;
  assign w4 = w1 << 2;
  assign w5 = w1 + w4;
  assign w160 = w5 << 5;
  assign w155 = w160 - w5;
  assign w320 = w5 << 6;
  assign w1183 = w1503 - w320;
  assign w620 = w155 << 2;
  assign w43 = w620 - w577;
  assign w5120 = w5 << 10;
  assign w6303 = w1183 + w5120;
  assign w640 = w5 << 7;
  assign w639 = w640 - w1;
  assign w256 = w1 << 8;
  assign w383 = w639 - w256;
  assign w794 = w155 + w639;
  assign w397 = w794 >> 1;
  assign w8 = w1 << 3;
  assign w631 = w639 - w8;
  assign w10224 = w639 << 4;
  assign w10801 = w577 + w10224;
  assign w1240 = w155 << 3;
  assign w263 = w1503 - w1240;
  assign w688 = w43 << 4;
  assign w425 = w688 - w263;
  assign w2104 = w263 << 3;
  assign w4199 = w6303 - w2104;
  assign w5504 = w43 << 7;
  assign w5241 = w5504 - w263;
  assign w3943 = w4199 - w256;
  assign w8398 = w4199 << 1;
  assign w8781 = w383 + w8398;
  assign w2366 = w1183 << 1;
  assign w227 = w2593 - w2366;
  assign w2048 = w1 << 11;
  assign w1821 = w2048 - w227;
  assign w4208 = w263 << 4;
  assign w3981 = w4208 - w227;
  assign w1816 = w227 << 3;
  assign w4487 = w6303 - w1816;
  assign w17562 = w8781 << 1;
  assign w17557 = w17562 - w5;
  assign w17492 = w17557 - w65;
  assign w4373 = w17492 >> 2;
  assign w766 = w383 << 1;
  assign w766_ = -1 * w766;
  assign w3943_ = -1 * w3943;
  assign w397_ = -1 * w397;
  assign w2480 = w155 << 4;
  assign w2480_ = -1 * w2480;
  assign w3006 = w1503 << 1;
  assign w8781_ = -1 * w8781;
  assign w2752 = w43 << 6;
  assign w1262 = w631 << 1;
  assign w10801_ = -1 * w10801;
  assign w3642 = w1821 << 1;
  assign w3642_ = -1 * w3642;
  assign w8398_ = -1 * w8398;
  assign w6303_ = -1 * w6303;
  assign w10372 = w2593 << 2;
  assign w10372_ = -1 * w10372;
  assign w850 = w425 << 1;
  assign w850_ = -1 * w850;
  assign w4616 = w577 << 3;
  assign w4616_ = -1 * w4616;

  assign Y[0] = w766_[46:15];
  assign Y[1] = w3943_[46:15];
  assign Y[2] = w397_[46:15];
  assign Y[3] = w2480_[46:15];
  assign Y[4] = w3006[46:15];
  assign Y[5] = w8781_[46:15];
  assign Y[6] = w2752[46:15];
  assign Y[7] = w1262[46:15];
  assign Y[8] = w4373[46:15];
  assign Y[9] = w10801_[46:15];
  assign Y[10] = w3642_[46:15];
  assign Y[11] = w3981[46:15];
  assign Y[12] = w8398_[46:15];
  assign Y[13] = w6303_[46:15];
  assign Y[14] = w4487[46:15];
  assign Y[15] = w1183[46:15];
  assign Y[16] = w10372_[46:15];
  assign Y[17] = w850_[46:15];
  assign Y[18] = w4616_[46:15];
  assign Y[19] = w5241[46:15];

endmodule //multiplier_block
