/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r18 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w8,
    w7,
    w56,
    w55,
    w256,
    w249,
    w47,
    w4,
    w51,
    w1792,
    w1741,
    w49,
    w376,
    w425,
    w1568,
    w1561,
    w3136,
    w3137,
    w3584,
    w3535,
    w1024,
    w537,
    w5096,
    w637,
    w3911,
    w6274,
    w4713,
    w5041,
    w4762,
    w2381,
    w2630,
    w1315,
    w4707,
    w5517,
    w13928,
    w9215,
    w996,
    w8219,
    w1632,
    w10847,
    w28280,
    w24369,
    w27200,
    w2831,
    w204,
    w204_,
    w8592,
    w1315_,
    w8219_,
    w47_,
    w11034,
    w6274_,
    w3520,
    w15936,
    w5041_;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w7 = w8 - w1;
  assign w56 = w7 << 3;
  assign w55 = w56 - w1;
  assign w256 = w1 << 8;
  assign w249 = w256 - w7;
  assign w47 = w55 - w8;
  assign w4 = w1 << 2;
  assign w51 = w55 - w4;
  assign w1792 = w7 << 8;
  assign w1741 = w1792 - w51;
  assign w49 = w56 - w7;
  assign w376 = w47 << 3;
  assign w425 = w49 + w376;
  assign w1568 = w49 << 5;
  assign w1561 = w1568 - w7;
  assign w3136 = w49 << 6;
  assign w3137 = w1 + w3136;
  assign w3584 = w7 << 9;
  assign w3535 = w3584 - w49;
  assign w1024 = w1 << 10;
  assign w537 = w1561 - w1024;
  assign w5096 = w1561 + w3535;
  assign w637 = w5096 >> 3;
  assign w3911 = w3535 + w376;
  assign w6274 = w3137 << 1;
  assign w4713 = w6274 - w1561;
  assign w5041 = w5096 - w55;
  assign w4762 = w49 + w4713;
  assign w2381 = w4762 >> 1;
  assign w2630 = w249 + w2381;
  assign w1315 = w2630 >> 1;
  assign w4707 = w4762 - w55;
  assign w5517 = w2381 + w3136;
  assign w13928 = w1741 << 3;
  assign w9215 = w13928 - w4713;
  assign w996 = w249 << 2;
  assign w8219 = w9215 - w996;
  assign w1632 = w51 << 5;
  assign w10847 = w9215 + w1632;
  assign w28280 = w3535 << 3;
  assign w24369 = w28280 - w3911;
  assign w27200 = w425 << 6;
  assign w2831 = w27200 - w24369;
  assign w204 = w51 << 2;
  assign w204_ = -1 * w204;
  assign w8592 = w537 << 4;
  assign w1315_ = -1 * w1315;
  assign w8219_ = -1 * w8219;
  assign w47_ = -1 * w47;
  assign w11034 = w5517 << 1;
  assign w6274_ = -1 * w6274;
  assign w3520 = w55 << 6;
  assign w15936 = w249 << 6;
  assign w5041_ = -1 * w5041;

  assign Y[0] = w425[46:15];
  assign Y[1] = w204_[46:15];
  assign Y[2] = w10847[46:15];
  assign Y[3] = w3535[46:15];
  assign Y[4] = w4707[46:15];
  assign Y[5] = w8592[46:15];
  assign Y[6] = w1315_[46:15];
  assign Y[7] = w1561[46:15];
  assign Y[8] = w8219_[46:15];
  assign Y[9] = w47_[46:15];
  assign Y[10] = w1741[46:15];
  assign Y[11] = w11034[46:15];
  assign Y[12] = w4713[46:15];
  assign Y[13] = w6274_[46:15];
  assign Y[14] = w2831[46:15];
  assign Y[15] = w5096[46:15];
  assign Y[16] = w3520[46:15];
  assign Y[17] = w15936[46:15];
  assign Y[18] = w5041_[46:15];
  assign Y[19] = w3911[46:15];

endmodule //multiplier_block
