/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r13 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w4,
    w5,
    w512,
    w517,
    w256,
    w773,
    w1034,
    w1039,
    w4136,
    w4141,
    w8272,
    w8273,
    w40,
    w41,
    w16,
    w57,
    w128,
    w87,
    w4156,
    w4115,
    w1312,
    w1353,
    w2126,
    w1063,
    w10,
    w1363,
    w5412,
    w5417,
    w5469,
    w4096,
    w2733,
    w348,
    w2385,
    w2784,
    w5517,
    w8504,
    w5771,
    w1392,
    w4379,
    w10938,
    w6559,
    w8230,
    w9593,
    w9650,
    w4825,
    w14592,
    w4999,
    w22068,
    w12475,
    w14860,
    w3715,
    w7296,
    w5179,
    w5771_,
    w2078,
    w1363_,
    w4770,
    w4770_,
    w696,
    w696_,
    w4999_,
    w4379_,
    w1546,
    w1546_,
    w3715_,
    w10358,
    w1824,
    w1824_,
    w1063_,
    w5417_,
    w6559_;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w5 = w1 + w4;
  assign w512 = w1 << 9;
  assign w517 = w5 + w512;
  assign w256 = w1 << 8;
  assign w773 = w517 + w256;
  assign w1034 = w517 << 1;
  assign w1039 = w5 + w1034;
  assign w4136 = w517 << 3;
  assign w4141 = w5 + w4136;
  assign w8272 = w517 << 4;
  assign w8273 = w1 + w8272;
  assign w40 = w5 << 3;
  assign w41 = w1 + w40;
  assign w16 = w1 << 4;
  assign w57 = w41 + w16;
  assign w128 = w1 << 7;
  assign w87 = w128 - w41;
  assign w4156 = w1039 << 2;
  assign w4115 = w4156 - w41;
  assign w1312 = w41 << 5;
  assign w1353 = w41 + w1312;
  assign w2126 = w773 + w1353;
  assign w1063 = w2126 >> 1;
  assign w10 = w5 << 1;
  assign w1363 = w1353 + w10;
  assign w5412 = w1353 << 2;
  assign w5417 = w5 + w5412;
  assign w5469 = w57 + w5412;
  assign w4096 = w1 << 12;
  assign w2733 = w4096 - w1363;
  assign w348 = w87 << 2;
  assign w2385 = w2733 - w348;
  assign w2784 = w87 << 5;
  assign w5517 = w2733 + w2784;
  assign w8504 = w1063 << 3;
  assign w5771 = w8504 - w2733;
  assign w1392 = w87 << 4;
  assign w4379 = w5771 - w1392;
  assign w10938 = w5469 << 1;
  assign w6559 = w10938 - w4379;
  assign w8230 = w4115 << 1;
  assign w9593 = w1363 + w8230;
  assign w9650 = w57 + w9593;
  assign w4825 = w9650 >> 1;
  assign w14592 = w57 << 8;
  assign w4999 = w14592 - w9593;
  assign w22068 = w5517 << 2;
  assign w12475 = w22068 - w9593;
  assign w14860 = w2385 + w12475;
  assign w3715 = w14860 >> 2;
  assign w7296 = w57 << 7;
  assign w5179 = w12475 - w7296;
  assign w5771_ = -1 * w5771;
  assign w2078 = w1039 << 1;
  assign w1363_ = -1 * w1363;
  assign w4770 = w2385 << 1;
  assign w4770_ = -1 * w4770;
  assign w696 = w87 << 3;
  assign w696_ = -1 * w696;
  assign w4999_ = -1 * w4999;
  assign w4379_ = -1 * w4379;
  assign w1546 = w773 << 1;
  assign w1546_ = -1 * w1546;
  assign w3715_ = -1 * w3715;
  assign w10358 = w5179 << 1;
  assign w1824 = w57 << 5;
  assign w1824_ = -1 * w1824;
  assign w1063_ = -1 * w1063;
  assign w5417_ = -1 * w5417;
  assign w6559_ = -1 * w6559;

  assign Y[0] = w10938[46:15];
  assign Y[1] = w5771_[46:15];
  assign Y[2] = w8230[46:15];
  assign Y[3] = w2078[46:15];
  assign Y[4] = w1363_[46:15];
  assign Y[5] = w4770_[46:15];
  assign Y[6] = w696_[46:15];
  assign Y[7] = w4999_[46:15];
  assign Y[8] = w4379_[46:15];
  assign Y[9] = w4825[46:15];
  assign Y[10] = w1546_[46:15];
  assign Y[11] = w3715_[46:15];
  assign Y[12] = w10358[46:15];
  assign Y[13] = w1824_[46:15];
  assign Y[14] = w1063_[46:15];
  assign Y[15] = w5417_[46:15];
  assign Y[16] = w5517[46:15];
  assign Y[17] = w6559_[46:15];
  assign Y[18] = w4141[46:15];
  assign Y[19] = w8273[46:15];

endmodule //multiplier_block
