/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r9 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w4,
    w5,
    w128,
    w123,
    w2048,
    w1925,
    w1968,
    w1963,
    w3893,
    w256,
    w4149,
    w160,
    w161,
    w644,
    w767,
    w1280,
    w1119,
    w8192,
    w8353,
    w806,
    w403,
    w32,
    w1087,
    w1645,
    w3926,
    w3159,
    w3562,
    w1781,
    w40,
    w3119,
    w8696,
    w5537,
    w4900,
    w1225,
    w3675,
    w3547,
    w322,
    w3997,
    w7350,
    w5387,
    w6136,
    w2589,
    w16,
    w11,
    w1534,
    w1523,
    w5632,
    w5509,
    w4149_,
    w4476,
    w4476_,
    w6092,
    w7094,
    w7094_,
    w3224,
    w7124,
    w7124_,
    w4348,
    w4348_,
    w7994,
    w3068,
    w3068_,
    w3893_,
    w11018,
    w5537_;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w5 = w1 + w4;
  assign w128 = w1 << 7;
  assign w123 = w128 - w5;
  assign w2048 = w1 << 11;
  assign w1925 = w2048 - w123;
  assign w1968 = w123 << 4;
  assign w1963 = w1968 - w5;
  assign w3893 = w1925 + w1968;
  assign w256 = w1 << 8;
  assign w4149 = w3893 + w256;
  assign w160 = w5 << 5;
  assign w161 = w1 + w160;
  assign w644 = w161 << 2;
  assign w767 = w123 + w644;
  assign w1280 = w5 << 8;
  assign w1119 = w1280 - w161;
  assign w8192 = w1 << 13;
  assign w8353 = w161 + w8192;
  assign w806 = w1925 - w1119;
  assign w403 = w806 >> 1;
  assign w32 = w1 << 5;
  assign w1087 = w1119 - w32;
  assign w1645 = w2048 - w403;
  assign w3926 = w1963 << 1;
  assign w3159 = w3926 - w767;
  assign w3562 = w403 + w3159;
  assign w1781 = w3562 >> 1;
  assign w40 = w5 << 3;
  assign w3119 = w3159 - w40;
  assign w8696 = w1087 << 3;
  assign w5537 = w8696 - w3159;
  assign w4900 = w1781 + w3119;
  assign w1225 = w4900 >> 2;
  assign w3675 = w4900 - w1225;
  assign w3547 = w3675 - w128;
  assign w322 = w161 << 1;
  assign w3997 = w3675 + w322;
  assign w7350 = w3675 << 1;
  assign w5387 = w7350 - w1963;
  assign w6136 = w767 << 3;
  assign w2589 = w6136 - w3547;
  assign w16 = w1 << 4;
  assign w11 = w16 - w5;
  assign w1534 = w767 << 1;
  assign w1523 = w1534 - w11;
  assign w5632 = w11 << 9;
  assign w5509 = w5632 - w123;
  assign w4149_ = -1 * w4149;
  assign w4476 = w1119 << 2;
  assign w4476_ = -1 * w4476;
  assign w6092 = w1523 << 2;
  assign w7094 = w3547 << 1;
  assign w7094_ = -1 * w7094;
  assign w3224 = w403 << 3;
  assign w7124 = w1781 << 2;
  assign w7124_ = -1 * w7124;
  assign w4348 = w1087 << 2;
  assign w4348_ = -1 * w4348;
  assign w7994 = w3997 << 1;
  assign w3068 = w767 << 2;
  assign w3068_ = -1 * w3068;
  assign w3893_ = -1 * w3893;
  assign w11018 = w5509 << 1;
  assign w5537_ = -1 * w5537;

  assign Y[0] = w4149_[46:15];
  assign Y[1] = w5387[46:15];
  assign Y[2] = w4476_[46:15];
  assign Y[3] = w4900[46:15];
  assign Y[4] = w1963[46:15];
  assign Y[5] = w6092[46:15];
  assign Y[6] = w7094_[46:15];
  assign Y[7] = w3224[46:15];
  assign Y[8] = w1645[46:15];
  assign Y[9] = w7124_[46:15];
  assign Y[10] = w4348_[46:15];
  assign Y[11] = w2589[46:15];
  assign Y[12] = w7994[46:15];
  assign Y[13] = w1925[46:15];
  assign Y[14] = w3068_[46:15];
  assign Y[15] = w3893_[46:15];
  assign Y[16] = w8353[46:15];
  assign Y[17] = w3119[46:15];
  assign Y[18] = w11018[46:15];
  assign Y[19] = w5537_[46:15];

endmodule //multiplier_block
