
/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r17 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

 // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w4,
    w5,
    w20,
    w25,
    w80,
    w105,
    w106,
    w53,
    w424,
    w477,
    w482,
    w241,
    w50,
    w427,
    w512,
    w989,
    w8192,
    w7715,
    w1680,
    w691,
    w1024,
    w1451,
    w7690,
    w3845,
    w848,
    w2997,
    w320,
    w3525,
    w3392,
    w4083,
    w11988,
    w11511,
    w11752,
    w1469,
    w6832,
    w4679,
    w497,
    w5176,
    w647,
    w994,
    w2445,
    w3976,
    w4001,
    w20480,
    w20455,
    w19808,
    w619,
    w2445_,
    w1928,
    w2902,
    w1469_,
    w210,
    w1696,
    w1696_,
    w5994,
    w1382,
    w1600,
    w3525_,
    w3416,
    w11511_,
    w989_;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w5 = w1 + w4;
  assign w20 = w5 << 2;
  assign w25 = w5 + w20;
  assign w80 = w5 << 4;
  assign w105 = w25 + w80;
  assign w106 = w1 + w105;
  assign w53 = w106 >> 1;
  assign w424 = w53 << 3;
  assign w477 = w53 + w424;
  assign w482 = w5 + w477;
  assign w241 = w482 >> 1;
  assign w50 = w25 << 1;
  assign w427 = w477 - w50;
  assign w512 = w1 << 9;
  assign w989 = w477 + w512;
  assign w8192 = w1 << 13;
  assign w7715 = w8192 - w477;
  assign w1680 = w105 << 4;
  assign w691 = w1680 - w989;
  assign w1024 = w1 << 10;
  assign w1451 = w427 + w1024;
  assign w7690 = w7715 - w25;
  assign w3845 = w7690 >> 1;
  assign w848 = w53 << 4;
  assign w2997 = w3845 - w848;
  assign w320 = w5 << 6;
  assign w3525 = w3845 - w320;
  assign w3392 = w53 << 6;
  assign w4083 = w691 + w3392;
  assign w11988 = w2997 << 2;
  assign w11511 = w11988 - w477;
  assign w11752 = w241 + w11511;
  assign w1469 = w11752 >> 3;
  assign w6832 = w427 << 4;
  assign w4679 = w11511 - w6832;
  assign w497 = w477 + w20;
  assign w5176 = w4679 + w497;
  assign w647 = w5176 >> 3;
  assign w994 = w497 << 1;
  assign w2445 = w1451 + w994;
  assign w3976 = w497 << 3;
  assign w4001 = w25 + w3976;
  assign w20480 = w5 << 12;
  assign w20455 = w20480 - w25;
  assign w19808 = w20455 - w647;
  assign w619 = w19808 >> 5;
  assign w2445_ = -1 * w2445;
  assign w1928 = w241 << 3;
  assign w2902 = w1451 << 1;
  assign w1469_ = -1 * w1469;
  assign w210 = w105 << 1;
  assign w1696 = w53 << 5;
  assign w1696_ = -1 * w1696;
  assign w5994 = w2997 << 1;
  assign w1382 = w691 << 1;
  assign w1600 = w25 << 6;
  assign w3525_ = -1 * w3525;
  assign w3416 = w427 << 3;
  assign w11511_ = -1 * w11511;
  assign w989_ = -1 * w989;

  assign Y[0] = w7715[46:15];
  assign Y[1] = w2445_[46:15];
  assign Y[2] = w647[46:15];
  assign Y[3] = w1928[46:15];
  assign Y[4] = w4679[46:15];
  assign Y[5] = w619[46:15];
  assign Y[6] = w2902[46:15];
  assign Y[7] = w1469_[46:15];
  assign Y[8] = w210[46:15];
  assign Y[9] = w1696_[46:15];
  assign Y[10] = w7690[46:15];
  assign Y[11] = w5994[46:15];
  assign Y[12] = w4001[46:15];
  assign Y[13] = w1382[46:15];
  assign Y[14] = w4083[46:15];
  assign Y[15] = w1600[46:15];
  assign Y[16] = w3525_[46:15];
  assign Y[17] = w3416[46:15];
  assign Y[18] = w11511_[46:15];
  assign Y[19] = w989_[46:15];

endmodule //multiplier_block
