/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r16 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w4,
    w5,
    w5120,
    w5121,
    w64,
    w69,
    w1104,
    w1173,
    w1280,
    w1349,
    w40,
    w1389,
    w276,
    w1113,
    w256,
    w857,
    w8,
    w1121,
    w8832,
    w7719,
    w2401,
    w1012,
    w253,
    w128,
    w2273,
    w4802,
    w3629,
    w4452,
    w6853,
    w2024,
    w2025,
    w9604,
    w7331,
    w8096,
    w9445,
    w77,
    w4928,
    w3815,
    w154,
    w7565,
    w8019,
    w6856,
    w14575,
    w6556,
    w1639,
    w22140,
    w5535,
    w32384,
    w32637,
    w32632,
    w4079,
    w10242,
    w9092,
    w16038,
    w11070,
    w3815_,
    w2025_,
    w2346,
    w2346_,
    w6853_,
    w253_,
    w1389_,
    w2698,
    w2698_,
    w8158,
    w8158_,
    w6556_;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w5 = w1 + w4;
  assign w5120 = w5 << 10;
  assign w5121 = w1 + w5120;
  assign w64 = w1 << 6;
  assign w69 = w5 + w64;
  assign w1104 = w69 << 4;
  assign w1173 = w69 + w1104;
  assign w1280 = w5 << 8;
  assign w1349 = w69 + w1280;
  assign w40 = w5 << 3;
  assign w1389 = w1349 + w40;
  assign w276 = w69 << 2;
  assign w1113 = w1389 - w276;
  assign w256 = w1 << 8;
  assign w857 = w1113 - w256;
  assign w8 = w1 << 3;
  assign w1121 = w1113 + w8;
  assign w8832 = w69 << 7;
  assign w7719 = w8832 - w1113;
  assign w2401 = w1121 + w1280;
  assign w1012 = w2401 - w1389;
  assign w253 = w1012 >> 2;
  assign w128 = w1 << 7;
  assign w2273 = w2401 - w128;
  assign w4802 = w2401 << 1;
  assign w3629 = w4802 - w1173;
  assign w4452 = w1113 << 2;
  assign w6853 = w2401 + w4452;
  assign w2024 = w253 << 3;
  assign w2025 = w1 + w2024;
  assign w9604 = w2401 << 2;
  assign w7331 = w9604 - w2273;
  assign w8096 = w253 << 5;
  assign w9445 = w1349 + w8096;
  assign w77 = w69 + w8;
  assign w4928 = w77 << 6;
  assign w3815 = w4928 - w1113;
  assign w154 = w77 << 1;
  assign w7565 = w7719 - w154;
  assign w8019 = w8096 - w77;
  assign w6856 = w857 << 3;
  assign w14575 = w7719 + w6856;
  assign w6556 = w14575 - w8019;
  assign w1639 = w6556 >> 2;
  assign w22140 = w7565 + w14575;
  assign w5535 = w22140 >> 2;
  assign w32384 = w253 << 7;
  assign w32637 = w253 + w32384;
  assign w32632 = w32637 - w5;
  assign w4079 = w32632 >> 3;
  assign w10242 = w5121 << 1;
  assign w9092 = w2273 << 2;
  assign w16038 = w8019 << 1;
  assign w11070 = w5535 << 1;
  assign w3815_ = -1 * w3815;
  assign w2025_ = -1 * w2025;
  assign w2346 = w1173 << 1;
  assign w2346_ = -1 * w2346;
  assign w6853_ = -1 * w6853;
  assign w253_ = -1 * w253;
  assign w1389_ = -1 * w1389;
  assign w2698 = w1349 << 1;
  assign w2698_ = -1 * w2698;
  assign w8158 = w4079 << 1;
  assign w8158_ = -1 * w8158;
  assign w6556_ = -1 * w6556;

  assign Y[0] = w10242[46:15];
  assign Y[1] = w9092[46:15];
  assign Y[2] = w16038[46:15];
  assign Y[3] = w11070[46:15];
  assign Y[4] = w3815_[46:15];
  assign Y[5] = w857[46:15];
  assign Y[6] = w2025_[46:15];
  assign Y[7] = w2346_[46:15];
  assign Y[8] = w3629[46:15];
  assign Y[9] = w6853_[46:15];
  assign Y[10] = w253_[46:15];
  assign Y[11] = w7331[46:15];
  assign Y[12] = w9445[46:15];
  assign Y[13] = w1121[46:15];
  assign Y[14] = w1389_[46:15];
  assign Y[15] = w2698_[46:15];
  assign Y[16] = w7719[46:15];
  assign Y[17] = w7565[46:15];
  assign Y[18] = w8158_[46:15];
  assign Y[19] = w6556_[46:15];

endmodule //multiplier_block
