/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r1 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w4,
    w3,
    w768,
    w771,
    w32,
    w35,
    w6,
    w41,
    w280,
    w283,
    w1120,
    w1123,
    w4096,
    w4131,
    w164,
    w119,
    w560,
    w679,
    w952,
    w1235,
    w2264,
    w2145,
    w3072,
    w2953,
    w1585,
    w1132,
    w2367,
    w8580,
    w10947,
    w328,
    w1817,
    w82,
    w1899,
    w1358,
    w3175,
    w3634,
    w3669,
    w64,
    w61,
    w976,
    w2099,
    w122,
    w3297,
    w7808,
    w5441,
    w8396,
    w12527,
    w6340,
    w6187,
    w5248,
    w7279,
    w2246,
    w3170,
    w3170_,
    w3084,
    w3084_,
    w2953_,
    w4940,
    w7279_,
    w3798,
    w3798_,
    w6350,
    w566,
    w3297_,
    w5432,
    w4734,
    w4734_,
    w10947_,
    w4198,
    w4198_;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w3 = w4 - w1;
  assign w768 = w3 << 8;
  assign w771 = w3 + w768;
  assign w32 = w1 << 5;
  assign w35 = w3 + w32;
  assign w6 = w3 << 1;
  assign w41 = w35 + w6;
  assign w280 = w35 << 3;
  assign w283 = w3 + w280;
  assign w1120 = w35 << 5;
  assign w1123 = w3 + w1120;
  assign w4096 = w1 << 12;
  assign w4131 = w35 + w4096;
  assign w164 = w41 << 2;
  assign w119 = w283 - w164;
  assign w560 = w35 << 4;
  assign w679 = w119 + w560;
  assign w952 = w119 << 3;
  assign w1235 = w283 + w952;
  assign w2264 = w283 << 3;
  assign w2145 = w2264 - w119;
  assign w3072 = w3 << 10;
  assign w2953 = w3072 - w119;
  assign w1585 = w2145 - w560;
  assign w1132 = w283 << 2;
  assign w2367 = w1235 + w1132;
  assign w8580 = w2145 << 2;
  assign w10947 = w2367 + w8580;
  assign w328 = w41 << 3;
  assign w1817 = w2145 - w328;
  assign w82 = w41 << 1;
  assign w1899 = w1817 + w82;
  assign w1358 = w679 << 1;
  assign w3175 = w1817 + w1358;
  assign w3634 = w1817 << 1;
  assign w3669 = w35 + w3634;
  assign w64 = w1 << 6;
  assign w61 = w64 - w3;
  assign w976 = w61 << 4;
  assign w2099 = w1123 + w976;
  assign w122 = w61 << 1;
  assign w3297 = w3175 + w122;
  assign w7808 = w61 << 7;
  assign w5441 = w7808 - w2367;
  assign w8396 = w2099 << 2;
  assign w12527 = w4131 + w8396;
  assign w6340 = w1585 << 2;
  assign w6187 = w12527 - w6340;
  assign w5248 = w41 << 7;
  assign w7279 = w12527 - w5248;
  assign w2246 = w1123 << 1;
  assign w3170 = w1585 << 1;
  assign w3170_ = -1 * w3170;
  assign w3084 = w771 << 2;
  assign w3084_ = -1 * w3084;
  assign w2953_ = -1 * w2953;
  assign w4940 = w1235 << 2;
  assign w7279_ = -1 * w7279;
  assign w3798 = w1899 << 1;
  assign w3798_ = -1 * w3798;
  assign w6350 = w3175 << 1;
  assign w566 = w283 << 1;
  assign w3297_ = -1 * w3297;
  assign w5432 = w679 << 3;
  assign w4734 = w2367 << 1;
  assign w4734_ = -1 * w4734;
  assign w10947_ = -1 * w10947;
  assign w4198 = w2099 << 1;
  assign w4198_ = -1 * w4198;

  assign Y[0] = w2246[46:15];
  assign Y[1] = w4131[46:15];
  assign Y[2] = w2145[46:15];
  assign Y[3] = w3170_[46:15];
  assign Y[4] = w5441[46:15];
  assign Y[5] = w3084_[46:15];
  assign Y[6] = w2953_[46:15];
  assign Y[7] = w4940[46:15];
  assign Y[8] = w7279_[46:15];
  assign Y[9] = w41[46:15];
  assign Y[10] = w3798_[46:15];
  assign Y[11] = w6350[46:15];
  assign Y[12] = w3669[46:15];
  assign Y[13] = w6187[46:15];
  assign Y[14] = w566[46:15];
  assign Y[15] = w3297_[46:15];
  assign Y[16] = w5432[46:15];
  assign Y[17] = w4734_[46:15];
  assign Y[18] = w10947_[46:15];
  assign Y[19] = w4198_[46:15];

endmodule //multiplier_block