/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r7 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w8,
    w7,
    w224,
    w223,
    w446,
    w453,
    w892,
    w893,
    w56,
    w837,
    w838,
    w419,
    w1676,
    w2569,
    w1812,
    w757,
    w4096,
    w1527,
    w3015,
    w1792,
    w955,
    w14,
    w969,
    w3820,
    w1251,
    w1514,
    w2469,
    w7640,
    w5071,
    w4652,
    w1163,
    w406,
    w203,
    w2048,
    w3211,
    w9304,
    w9297,
    w6696,
    w5859,
    w7022,
    w3511,
    w1784,
    w4075,
    w10276,
    w4417,
    w4431,
    w198,
    w99,
    w6336,
    w5173,
    w3168,
    w8239,
    w1786,
    w1786_,
    w8834,
    w906,
    w4431_,
    w3211_,
    w3054,
    w3054_,
    w1514_,
    w7022_,
    w3015_,
    w2502,
    w2502_,
    w3348,
    w7752,
    w838_,
    w4938,
    w4938_;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w7 = w8 - w1;
  assign w224 = w7 << 5;
  assign w223 = w224 - w1;
  assign w446 = w223 << 1;
  assign w453 = w7 + w446;
  assign w892 = w223 << 2;
  assign w893 = w1 + w892;
  assign w56 = w7 << 3;
  assign w837 = w893 - w56;
  assign w838 = w1 + w837;
  assign w419 = w838 >> 1;
  assign w1676 = w419 << 2;
  assign w2569 = w893 + w1676;
  assign w1812 = w453 << 2;
  assign w757 = w2569 - w1812;
  assign w4096 = w1 << 12;
  assign w1527 = w4096 - w2569;
  assign w3015 = w2569 + w446;
  assign w1792 = w7 << 8;
  assign w955 = w1792 - w837;
  assign w14 = w7 << 1;
  assign w969 = w955 + w14;
  assign w3820 = w955 << 2;
  assign w1251 = w3820 - w2569;
  assign w1514 = w757 << 1;
  assign w2469 = w955 + w1514;
  assign w7640 = w955 << 3;
  assign w5071 = w7640 - w2569;
  assign w4652 = w5071 - w419;
  assign w1163 = w4652 >> 2;
  assign w406 = w1163 - w757;
  assign w203 = w406 >> 1;
  assign w2048 = w1 << 11;
  assign w3211 = w1163 + w2048;
  assign w9304 = w1163 << 3;
  assign w9297 = w9304 - w7;
  assign w6696 = w837 << 3;
  assign w5859 = w6696 - w837;
  assign w7022 = w1163 + w5859;
  assign w3511 = w7022 >> 1;
  assign w1784 = w223 << 3;
  assign w4075 = w5859 - w1784;
  assign w10276 = w2569 << 2;
  assign w4417 = w10276 - w5859;
  assign w4431 = w4417 + w14;
  assign w198 = w955 - w757;
  assign w99 = w198 >> 1;
  assign w6336 = w99 << 6;
  assign w5173 = w6336 - w1163;
  assign w3168 = w99 << 5;
  assign w8239 = w5071 + w3168;
  assign w1786 = w893 << 1;
  assign w1786_ = -1 * w1786;
  assign w8834 = w4417 << 1;
  assign w906 = w453 << 1;
  assign w4431_ = -1 * w4431;
  assign w3211_ = -1 * w3211;
  assign w3054 = w1527 << 1;
  assign w3054_ = -1 * w3054;
  assign w1514_ = -1 * w1514;
  assign w7022_ = -1 * w7022;
  assign w3015_ = -1 * w3015;
  assign w2502 = w1251 << 1;
  assign w2502_ = -1 * w2502;
  assign w3348 = w837 << 2;
  assign w7752 = w969 << 3;
  assign w838_ = -1 * w838;
  assign w4938 = w2469 << 1;
  assign w4938_ = -1 * w4938;

  assign Y[0] = w1786_[46:15];
  assign Y[1] = w5173[46:15];
  assign Y[2] = w8834[46:15];
  assign Y[3] = w8239[46:15];
  assign Y[4] = w906[46:15];
  assign Y[5] = w4431_[46:15];
  assign Y[6] = w3211_[46:15];
  assign Y[7] = w5071[46:15];
  assign Y[8] = w3054_[46:15];
  assign Y[9] = w1514_[46:15];
  assign Y[10] = w7022_[46:15];
  assign Y[11] = w3015_[46:15];
  assign Y[12] = w4075[46:15];
  assign Y[13] = w2502_[46:15];
  assign Y[14] = w406[46:15];
  assign Y[15] = w3348[46:15];
  assign Y[16] = w9297[46:15];
  assign Y[17] = w7752[46:15];
  assign Y[18] = w838_[46:15];
  assign Y[19] = w4938_[46:15];

endmodule //multiplier_block
