/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r2 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w4,
    w3,
    w32,
    w33,
    w528,
    w527,
    w66,
    w69,
    w101,
    w276,
    w345,
    w1104,
    w1105,
    w1003,
    w348,
    w87,
    w768,
    w855,
    w2208,
    w2295,
    w2784,
    w3787,
    w5568,
    w4463,
    w6840,
    w6313,
    w2210,
    w1577,
    w6308,
    w1845,
    w3154,
    w3085,
    w12621,
    w4416,
    w1331,
    w6170,
    w7173,
    w11136,
    w3963,
    w17680,
    w10507,
    w8192,
    w5897,
    w6464,
    w567,
    w48,
    w5945,
    w7380,
    w1054,
    w1054_,
    w4590,
    w4590_,
    w8840,
    w96,
    w96_,
    w7926,
    w7926_,
    w12626,
    w12626_,
    w690,
    w3420,
    w808,
    w33_,
    w10507_,
    w12621_,
    w2006,
    w2006_;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w3 = w4 - w1;
  assign w32 = w1 << 5;
  assign w33 = w1 + w32;
  assign w528 = w33 << 4;
  assign w527 = w528 - w1;
  assign w66 = w33 << 1;
  assign w69 = w3 + w66;
  assign w101 = w69 + w32;
  assign w276 = w69 << 2;
  assign w345 = w69 + w276;
  assign w1104 = w69 << 4;
  assign w1105 = w1 + w1104;
  assign w1003 = w1104 - w101;
  assign w348 = w3 + w345;
  assign w87 = w348 >> 2;
  assign w768 = w3 << 8;
  assign w855 = w87 + w768;
  assign w2208 = w69 << 5;
  assign w2295 = w87 + w2208;
  assign w2784 = w87 << 5;
  assign w3787 = w1003 + w2784;
  assign w5568 = w87 << 6;
  assign w4463 = w5568 - w1105;
  assign w6840 = w855 << 3;
  assign w6313 = w6840 - w527;
  assign w2210 = w1105 << 1;
  assign w1577 = w3787 - w2210;
  assign w6308 = w1577 << 2;
  assign w1845 = w6308 - w4463;
  assign w3154 = w1577 << 1;
  assign w3085 = w3154 - w69;
  assign w12621 = w6313 + w6308;
  assign w4416 = w69 << 6;
  assign w1331 = w4416 - w3085;
  assign w6170 = w3085 << 1;
  assign w7173 = w1003 + w6170;
  assign w11136 = w87 << 7;
  assign w3963 = w11136 - w7173;
  assign w17680 = w1105 << 4;
  assign w10507 = w17680 - w7173;
  assign w8192 = w1 << 13;
  assign w5897 = w8192 - w2295;
  assign w6464 = w101 << 6;
  assign w567 = w6464 - w5897;
  assign w48 = w3 << 4;
  assign w5945 = w5897 + w48;
  assign w7380 = w1845 << 2;
  assign w1054 = w527 << 1;
  assign w1054_ = -1 * w1054;
  assign w4590 = w2295 << 1;
  assign w4590_ = -1 * w4590;
  assign w8840 = w1105 << 3;
  assign w96 = w3 << 5;
  assign w96_ = -1 * w96;
  assign w7926 = w3963 << 1;
  assign w7926_ = -1 * w7926;
  assign w12626 = w6313 << 1;
  assign w12626_ = -1 * w12626;
  assign w690 = w345 << 1;
  assign w3420 = w855 << 2;
  assign w808 = w101 << 3;
  assign w33_ = -1 * w33;
  assign w10507_ = -1 * w10507;
  assign w12621_ = -1 * w12621;
  assign w2006 = w1003 << 1;
  assign w2006_ = -1 * w2006;

  assign Y[0] = w7380[46:15];
  assign Y[1] = w1054_[46:15];
  assign Y[2] = w4590_[46:15];
  assign Y[3] = w8840[46:15];
  assign Y[4] = w5945[46:15];
  assign Y[5] = w96_[46:15];
  assign Y[6] = w6170[46:15];
  assign Y[7] = w7926_[46:15];
  assign Y[8] = w3787[46:15];
  assign Y[9] = w1331[46:15];
  assign Y[10] = w4463[46:15];
  assign Y[11] = w12626_[46:15];
  assign Y[12] = w567[46:15];
  assign Y[13] = w690[46:15];
  assign Y[14] = w3420[46:15];
  assign Y[15] = w808[46:15];
  assign Y[16] = w33_[46:15];
  assign Y[17] = w10507_[46:15];
  assign Y[18] = w12621_[46:15];
  assign Y[19] = w2006_[46:15];

endmodule //multiplier_block