/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r8 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w8,
    w9,
    w18,
    w19,
    w608,
    w599,
    w1024,
    w1043,
    w256,
    w255,
    w76,
    w179,
    w2048,
    w1793,
    w4792,
    w4613,
    w4172,
    w5215,
    w3586,
    w1629,
    w2396,
    w2819,
    w7611,
    w16,
    w7627,
    w38,
    w29,
    w1856,
    w813,
    w7172,
    w7143,
    w11456,
    w11427,
    w1626,
    w1881,
    w4608,
    w3565,
    w116,
    w3449,
    w32,
    w3597,
    w5728,
    w9293,
    w8160,
    w10041,
    w14286,
    w4245,
    w10025,
    w2086,
    w2685,
    w2040,
    w4725,
    w8344,
    w5659,
    w4613_,
    w9584,
    w7194,
    w7611_,
    w3762,
    w3762_,
    w4725_,
    w4245_,
    w13008,
    w2819_,
    w9293_,
    w1043_,
    w3258,
    w3258_,
    w11427_;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w9 = w1 + w8;
  assign w18 = w9 << 1;
  assign w19 = w1 + w18;
  assign w608 = w19 << 5;
  assign w599 = w608 - w9;
  assign w1024 = w1 << 10;
  assign w1043 = w19 + w1024;
  assign w256 = w1 << 8;
  assign w255 = w256 - w1;
  assign w76 = w19 << 2;
  assign w179 = w255 - w76;
  assign w2048 = w1 << 11;
  assign w1793 = w2048 - w255;
  assign w4792 = w599 << 3;
  assign w4613 = w4792 - w179;
  assign w4172 = w1043 << 2;
  assign w5215 = w1043 + w4172;
  assign w3586 = w1793 << 1;
  assign w1629 = w5215 - w3586;
  assign w2396 = w599 << 2;
  assign w2819 = w5215 - w2396;
  assign w7611 = w5215 + w2396;
  assign w16 = w1 << 4;
  assign w7627 = w7611 + w16;
  assign w38 = w19 << 1;
  assign w29 = w38 - w9;
  assign w1856 = w29 << 6;
  assign w813 = w1856 - w1043;
  assign w7172 = w1793 << 2;
  assign w7143 = w7172 - w29;
  assign w11456 = w179 << 6;
  assign w11427 = w11456 - w29;
  assign w1626 = w813 << 1;
  assign w1881 = w255 + w1626;
  assign w4608 = w9 << 9;
  assign w3565 = w4608 - w1043;
  assign w116 = w29 << 2;
  assign w3449 = w3565 - w116;
  assign w32 = w1 << 5;
  assign w3597 = w3565 + w32;
  assign w5728 = w179 << 5;
  assign w9293 = w3565 + w5728;
  assign w8160 = w255 << 5;
  assign w10041 = w1881 + w8160;
  assign w14286 = w7143 << 1;
  assign w4245 = w14286 - w10041;
  assign w10025 = w10041 - w16;
  assign w2086 = w1043 << 1;
  assign w2685 = w599 + w2086;
  assign w2040 = w255 << 3;
  assign w4725 = w2685 + w2040;
  assign w8344 = w1043 << 3;
  assign w5659 = w8344 - w2685;
  assign w4613_ = -1 * w4613;
  assign w9584 = w599 << 4;
  assign w7194 = w3597 << 1;
  assign w7611_ = -1 * w7611;
  assign w3762 = w1881 << 1;
  assign w3762_ = -1 * w3762;
  assign w4725_ = -1 * w4725;
  assign w4245_ = -1 * w4245;
  assign w13008 = w813 << 4;
  assign w2819_ = -1 * w2819;
  assign w9293_ = -1 * w9293;
  assign w1043_ = -1 * w1043;
  assign w3258 = w1629 << 1;
  assign w3258_ = -1 * w3258;
  assign w11427_ = -1 * w11427;

  assign Y[0] = w4613_[46:15];
  assign Y[1] = w9584[46:15];
  assign Y[2] = w7194[46:15];
  assign Y[3] = w7611_[46:15];
  assign Y[4] = w3762_[46:15];
  assign Y[5] = w5659[46:15];
  assign Y[6] = w4725_[46:15];
  assign Y[7] = w7143[46:15];
  assign Y[8] = w3449[46:15];
  assign Y[9] = w4245_[46:15];
  assign Y[10] = w13008[46:15];
  assign Y[11] = w10025[46:15];
  assign Y[12] = w2819_[46:15];
  assign Y[13] = w9293_[46:15];
  assign Y[14] = w1043_[46:15];
  assign Y[15] = w7627[46:15];
  assign Y[16] = w179[46:15];
  assign Y[17] = w3258_[46:15];
  assign Y[18] = w1793[46:15];
  assign Y[19] = w11427_[46:15];

endmodule //multiplier_block
