/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r11 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w8,
    w7,
    w112,
    w111,
    w28,
    w83,
    w896,
    w785,
    w1776,
    w1693,
    w332,
    w1361,
    w1354,
    w677,
    w2708,
    w4401,
    w5312,
    w5311,
    w4634,
    w2317,
    w1792,
    w3519,
    w8019,
    w888,
    w1429,
    w2858,
    w2181,
    w1328,
    w2757,
    w1570,
    w2999,
    w3434,
    w1717,
    w7029,
    w10888,
    w10777,
    w7104,
    w3673,
    w448,
    w10329,
    w224,
    w3897,
    w7794,
    w7801,
    w18536,
    w18453,
    w18454,
    w9227,
    w6280,
    w12173,
    w664,
    w16038,
    w2181_,
    w1354_,
    w10888_,
    w7038,
    w7029_,
    w8802,
    w8802_,
    w7346,
    w2757_,
    w1693_,
    w6280_;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w7 = w8 - w1;
  assign w112 = w7 << 4;
  assign w111 = w112 - w1;
  assign w28 = w7 << 2;
  assign w83 = w111 - w28;
  assign w896 = w7 << 7;
  assign w785 = w896 - w111;
  assign w1776 = w111 << 4;
  assign w1693 = w1776 - w83;
  assign w332 = w83 << 2;
  assign w1361 = w1693 - w332;
  assign w1354 = w1361 - w7;
  assign w677 = w1354 >> 1;
  assign w2708 = w677 << 2;
  assign w4401 = w1693 + w2708;
  assign w5312 = w83 << 6;
  assign w5311 = w5312 - w1;
  assign w4634 = w5311 - w677;
  assign w2317 = w4634 >> 1;
  assign w1792 = w7 << 8;
  assign w3519 = w5311 - w1792;
  assign w8019 = w5311 + w2708;
  assign w888 = w111 << 3;
  assign w1429 = w2317 - w888;
  assign w2858 = w1429 << 1;
  assign w2181 = w2858 - w677;
  assign w1328 = w83 << 4;
  assign w2757 = w1429 + w1328;
  assign w1570 = w785 << 1;
  assign w2999 = w1429 + w1570;
  assign w3434 = w677 + w2757;
  assign w1717 = w3434 >> 1;
  assign w7029 = w1717 + w5312;
  assign w10888 = w1361 << 3;
  assign w10777 = w10888 - w111;
  assign w7104 = w111 << 6;
  assign w3673 = w10777 - w7104;
  assign w448 = w7 << 6;
  assign w10329 = w10777 - w448;
  assign w224 = w7 << 5;
  assign w3897 = w3673 + w224;
  assign w7794 = w3897 << 1;
  assign w7801 = w7 + w7794;
  assign w18536 = w2317 << 3;
  assign w18453 = w18536 - w83;
  assign w18454 = w1 + w18453;
  assign w9227 = w18454 >> 1;
  assign w6280 = w785 << 3;
  assign w12173 = w18453 - w6280;
  assign w664 = w83 << 3;
  assign w16038 = w8019 << 1;
  assign w2181_ = -1 * w2181;
  assign w1354_ = -1 * w1354;
  assign w10888_ = -1 * w10888;
  assign w7038 = w3519 << 1;
  assign w7029_ = -1 * w7029;
  assign w8802 = w4401 << 1;
  assign w8802_ = -1 * w8802;
  assign w7346 = w3673 << 1;
  assign w2757_ = -1 * w2757;
  assign w1693_ = -1 * w1693;
  assign w6280_ = -1 * w6280;

  assign Y[0] = w664[46:15];
  assign Y[1] = w2999[46:15];
  assign Y[2] = w9227[46:15];
  assign Y[3] = w4634[46:15];
  assign Y[4] = w7801[46:15];
  assign Y[5] = w1717[46:15];
  assign Y[6] = w16038[46:15];
  assign Y[7] = w2181_[46:15];
  assign Y[8] = w1354_[46:15];
  assign Y[9] = w10888_[46:15];
  assign Y[10] = w7038[46:15];
  assign Y[11] = w7029_[46:15];
  assign Y[12] = w12173[46:15];
  assign Y[13] = w8802_[46:15];
  assign Y[14] = w10329[46:15];
  assign Y[15] = w7346[46:15];
  assign Y[16] = w2757_[46:15];
  assign Y[17] = w1693_[46:15];
  assign Y[18] = w6280_[46:15];
  assign Y[19] = w3897[46:15];

endmodule //multiplier_block
