/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r5 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w16,
    w17,
    w32,
    w49,
    w4,
    w21,
    w84,
    w101,
    w336,
    w319,
    w512,
    w533,
    w1344,
    w1345,
    w3232,
    w3183,
    w1066,
    w4249,
    w5380,
    w1131,
    w196,
    w213,
    w808,
    w1021,
    w1704,
    w2237,
    w3136,
    w3349,
    w852,
    w5101,
    w6816,
    w7029,
    w685,
    w34,
    w719,
    w2780,
    w695,
    w691,
    w1390,
    w1411,
    w3313,
    w202,
    w1613,
    w2822,
    w4435,
    w6698,
    w6698_,
    w2690,
    w1568,
    w1568_,
    w1613_,
    w5101_,
    w4264,
    w4264_,
    w4249_,
    w1131_,
    w2876,
    w5644,
    w202_,
    w4435_,
    w2237_,
    w1382,
    w1382_,
    w2740,
    w6626,
    w6626_;

  assign w1 = X;
  assign w16 = w1 << 4;
  assign w17 = w1 + w16;
  assign w32 = w1 << 5;
  assign w49 = w17 + w32;
  assign w4 = w1 << 2;
  assign w21 = w17 + w4;
  assign w84 = w21 << 2;
  assign w101 = w17 + w84;
  assign w336 = w21 << 4;
  assign w319 = w336 - w17;
  assign w512 = w1 << 9;
  assign w533 = w21 + w512;
  assign w1344 = w21 << 6;
  assign w1345 = w1 + w1344;
  assign w3232 = w101 << 5;
  assign w3183 = w3232 - w49;
  assign w1066 = w533 << 1;
  assign w4249 = w3183 + w1066;
  assign w5380 = w1345 << 2;
  assign w1131 = w5380 - w4249;
  assign w196 = w49 << 2;
  assign w213 = w17 + w196;
  assign w808 = w101 << 3;
  assign w1021 = w213 + w808;
  assign w1704 = w213 << 3;
  assign w2237 = w533 + w1704;
  assign w3136 = w49 << 6;
  assign w3349 = w213 + w3136;
  assign w852 = w213 << 2;
  assign w5101 = w4249 + w852;
  assign w6816 = w213 << 5;
  assign w7029 = w213 + w6816;
  assign w685 = w1021 - w336;
  assign w34 = w17 << 1;
  assign w719 = w685 + w34;
  assign w2780 = w7029 - w4249;
  assign w695 = w2780 >> 2;
  assign w691 = w695 - w4;
  assign w1390 = w695 << 1;
  assign w1411 = w21 + w1390;
  assign w3313 = w533 + w2780;
  assign w202 = w101 << 1;
  assign w1613 = w1411 + w202;
  assign w2822 = w1411 << 1;
  assign w4435 = w1613 + w2822;
  assign w6698 = w3349 << 1;
  assign w6698_ = -1 * w6698;
  assign w2690 = w1345 << 1;
  assign w1568 = w49 << 5;
  assign w1568_ = -1 * w1568;
  assign w1613_ = -1 * w1613;
  assign w5101_ = -1 * w5101;
  assign w4264 = w533 << 3;
  assign w4264_ = -1 * w4264;
  assign w4249_ = -1 * w4249;
  assign w1131_ = -1 * w1131;
  assign w2876 = w719 << 2;
  assign w5644 = w1411 << 2;
  assign w202_ = -1 * w202;
  assign w4435_ = -1 * w4435;
  assign w2237_ = -1 * w2237;
  assign w1382 = w691 << 1;
  assign w1382_ = -1 * w1382;
  assign w2740 = w685 << 2;
  assign w6626 = w3313 << 1;
  assign w6626_ = -1 * w6626;

  assign Y[0] = w6698_[46:15];
  assign Y[1] = w1021[46:15];
  assign Y[2] = w7029[46:15];
  assign Y[3] = w2690[46:15];
  assign Y[4] = w1568_[46:15];
  assign Y[5] = w1613_[46:15];
  assign Y[6] = w5101_[46:15];
  assign Y[7] = w4264_[46:15];
  assign Y[8] = w4249_[46:15];
  assign Y[9] = w319[46:15];
  assign Y[10] = w1131_[46:15];
  assign Y[11] = w2876[46:15];
  assign Y[12] = w5644[46:15];
  assign Y[13] = w202_[46:15];
  assign Y[14] = w4435_[46:15];
  assign Y[15] = w2237_[46:15];
  assign Y[16] = w1382_[46:15];
  assign Y[17] = w2740[46:15];
  assign Y[18] = w3183[46:15];
  assign Y[19] = w6626_[46:15];

endmodule //multiplier_block
