/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module W_h2h_r14 (
    X,
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0]
    Y1,
    Y2,
    Y3,
    Y4,
    Y5,
    Y6,
    Y7,
    Y8,
    Y9,
    Y10,
    Y11,
    Y12,
    Y13,
    Y14,
    Y15,
    Y16,
    Y17,
    Y18,
    Y19,
    Y20;

  wire [31:0] Y [0:19];

  assign Y1 = Y[0];
  assign Y2 = Y[1];
  assign Y3 = Y[2];
  assign Y4 = Y[3];
  assign Y5 = Y[4];
  assign Y6 = Y[5];
  assign Y7 = Y[6];
  assign Y8 = Y[7];
  assign Y9 = Y[8];
  assign Y10 = Y[9];
  assign Y11 = Y[10];
  assign Y12 = Y[11];
  assign Y13 = Y[12];
  assign Y14 = Y[13];
  assign Y15 = Y[14];
  assign Y16 = Y[15];
  assign Y17 = Y[16];
  assign Y18 = Y[17];
  assign Y19 = Y[18];
  assign Y20 = Y[19];

  //Multipliers:

  wire signed [46:0]
    w1,
    w8,
    w9,
    w288,
    w287,
    w72,
    w215,
    w359,
    w1148,
    w1149,
    w4,
    w363,
    w1436,
    w1445,
    w32,
    w331,
    w43,
    w1480,
    w185,
    w16,
    w59,
    w4096,
    w4281,
    w5920,
    w5561,
    w472,
    w141,
    w1024,
    w883,
    w172,
    w711,
    w2752,
    w2567,
    w2204,
    w551,
    w2558,
    w1279,
    w4592,
    w7159,
    w22244,
    w27805,
    w28168,
    w3521,
    w18384,
    w9421,
    w3521_,
    w3532,
    w3532_,
    w10592,
    w10592_,
    w2904,
    w2904_,
    w5920_,
    w2298,
    w2298_,
    w5561_,
    w4281_,
    w1279_,
    w4408,
    w4408_,
    w9024,
    w9024_,
    w688,
    w688_,
    w2296,
    w718,
    w2890,
    w2890_,
    w711_,
    w9421_,
    w860;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w9 = w1 + w8;
  assign w288 = w9 << 5;
  assign w287 = w288 - w1;
  assign w72 = w9 << 3;
  assign w215 = w287 - w72;
  assign w359 = w287 + w72;
  assign w1148 = w287 << 2;
  assign w1149 = w1 + w1148;
  assign w4 = w1 << 2;
  assign w363 = w359 + w4;
  assign w1436 = w359 << 2;
  assign w1445 = w9 + w1436;
  assign w32 = w1 << 5;
  assign w331 = w363 - w32;
  assign w43 = w331 - w288;
  assign w1480 = w1149 + w331;
  assign w185 = w1480 >> 3;
  assign w16 = w1 << 4;
  assign w59 = w43 + w16;
  assign w4096 = w1 << 12;
  assign w4281 = w185 + w4096;
  assign w5920 = w185 << 5;
  assign w5561 = w5920 - w359;
  assign w472 = w59 << 3;
  assign w141 = w472 - w331;
  assign w1024 = w1 << 10;
  assign w883 = w1024 - w141;
  assign w172 = w43 << 2;
  assign w711 = w883 - w172;
  assign w2752 = w43 << 6;
  assign w2567 = w2752 - w185;
  assign w2204 = w2567 - w363;
  assign w551 = w2204 >> 2;
  assign w2558 = w2567 - w9;
  assign w1279 = w2558 >> 1;
  assign w4592 = w287 << 4;
  assign w7159 = w2567 + w4592;
  assign w22244 = w5561 << 2;
  assign w27805 = w5561 + w22244;
  assign w28168 = w363 + w27805;
  assign w3521 = w28168 >> 3;
  assign w18384 = w1149 << 4;
  assign w9421 = w27805 - w18384;
  assign w3521_ = -1 * w3521;
  assign w3532 = w883 << 2;
  assign w3532_ = -1 * w3532;
  assign w10592 = w331 << 5;
  assign w10592_ = -1 * w10592;
  assign w2904 = w363 << 3;
  assign w2904_ = -1 * w2904;
  assign w5920_ = -1 * w5920;
  assign w2298 = w1149 << 1;
  assign w2298_ = -1 * w2298;
  assign w5561_ = -1 * w5561;
  assign w4281_ = -1 * w4281;
  assign w1279_ = -1 * w1279;
  assign w4408 = w551 << 3;
  assign w4408_ = -1 * w4408;
  assign w9024 = w141 << 6;
  assign w9024_ = -1 * w9024;
  assign w688 = w43 << 4;
  assign w688_ = -1 * w688;
  assign w2296 = w287 << 3;
  assign w718 = w359 << 1;
  assign w2890 = w1445 << 1;
  assign w2890_ = -1 * w2890;
  assign w711_ = -1 * w711;
  assign w9421_ = -1 * w9421;
  assign w860 = w215 << 2;

  assign Y[0] = w3521_[46:15];
  assign Y[1] = w3532_[46:15];
  assign Y[2] = w472[46:15];
  assign Y[3] = w10592_[46:15];
  assign Y[4] = w2904_[46:15];
  assign Y[5] = w5920_[46:15];
  assign Y[6] = w2298_[46:15];
  assign Y[7] = w5561_[46:15];
  assign Y[8] = w7159[46:15];
  assign Y[9] = w4281_[46:15];
  assign Y[10] = w1279_[46:15];
  assign Y[11] = w4408_[46:15];
  assign Y[12] = w9024_[46:15];
  assign Y[13] = w688_[46:15];
  assign Y[14] = w2296[46:15];
  assign Y[15] = w718[46:15];
  assign Y[16] = w2890_[46:15];
  assign Y[17] = w711_[46:15];
  assign Y[18] = w9421_[46:15];
  assign Y[19] = w860[46:15];

endmodule //multiplier_block
